#!/bin/sh
# ``Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# The Initial Developer of the Original Code is Ericsson Utvecklings AB.
# Portions created by Ericsson are Copyright 1999-2000, Ericsson
# Utvecklings AB. All Rights Reserved.''
#

APP=
TITLE=
VSN=

while [ $# -gt 0 ]; do
    case $1 in
    -app)
        APP=$2;
	shift;
	shift;;
    -title)
	TITLE=$2;
	shift;
	shift;;
    -vsn)
	VSN=$2;
	shift;
	shift;;
    esac
done

if [ -n "$APP" -a -n "$TITLE" ] ; then
    erl -boot start_clean -noshell \
	-run edoc_run application $APP "\".\"" "[{title,$TITLE}]" \
	-s erlang halt
elif [ -n "$APP" -a -n "$VSN" ] ; then
    erl -boot start_clean -noshell \
	-run edoc_run application $APP "\".\"" "[{def,{vsn,\"$VSN\"}}]" \
	-s erlang halt
else
    echo "Usage: edoc_generate [-app Appname [-title Title |-vsn Vsn]]"
fi
