%% Generated by the Erlang ASN.1 compiler. Version: 5.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKCS-12.

-ifndef(_PKCS_12_HRL_).
-define(_PKCS_12_HRL_, true).

-record('AlgorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('Attribute', {
  type,
  values
}).

-record('DigestInfo', {
  digestAlgorithm,
  digest
}).

-record('ContentInfo', {
  contentType,
  content = asn1_NOVALUE
}).

-record('PFX', {
  version,
  authSafe,
  macData = asn1_NOVALUE
}).

-record('MacData', {
  mac,
  macSalt,
  iterations = asn1_DEFAULT
}).

-record('SafeBag', {
  bagId,
  bagValue,
  bagAttributes = asn1_NOVALUE
}).

-record('KeyBag', {
  version,
  algorithm,
  privateKey
}).

-record('CertBag', {
  certId,
  certValue
}).

-define('rsadsi', {1,2,840,113549}).
-define('pkcs', {1,2,840,113549,1}).
-define('pkcs-12', {1,2,840,113549,1,12}).
-endif. %% _PKCS_12_HRL_
