#! /bin/sh -f
# ``Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# The Initial Developer of the Original Code is Ericsson Utvecklings AB.
# Portions created by Ericsson are Copyright 1999, Ericsson Utvecklings
# AB. All Rights Reserved.''
# 
#     $Id$
#
#
# Author: Hakan Mattsson <hakan@erix.ericsson.se>
# Purpose: Simplified execution of the test suite
#    
# Usage: mt <args to erlang startup script>

#top=".."
top="$ERL_TOP/lib/mnesia"
h=`hostname`
p="-pa $top/examples -pa $top/ebin -pa $top/test -mnesia_test_verbose true"
log=test_log$$
latest=test_log_latest
args=${1+"$@"}
erlcmd="erl -sname a $p $args -mnesia_test_timeout"
erlcmd1="erl -sname a1 $p $args"
erlcmd2="erl -sname a2 $p $args"

xterm -geometry 70x20+0+550 -T a1 -e $erlcmd1 &
xterm -geometry 70x20+450+550 -T a2 -e $erlcmd2 &

rm "$latest" 2>/dev/null
ln -s "$log" "$latest"
touch "$log"

echo "$erlcmd1"
echo ""
echo "$erlcmd2"
echo ""
echo "$erlcmd"
echo ""
echo "Give the following command in order to see the outcome from node a@$h"":"
echo ""
echo "	less test_log$$"

ostype=`uname -s`
if [ "$ostype" = "SunOS" ] ; then 
  /usr/openwin/bin/xterm -geometry 145x40+0+0 -T a -l -lf "$log" -e $erlcmd &
else
  xterm -geometry 145x40+0+0 -T a -e script -f -c "$erlcmd" "$log"  &
fi
tail -f "$log" | egrep 'Eval|<>ERROR|NYI'

