//
// %CopyrightBegin%
//
// Copyright Ericsson AB 2001-2016. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// %CopyrightEnd%
//

#ifndef _EVENT_TEST_SERVER_IDL
#define _EVENT_TEST_SERVER_IDL

#include <../src/CosEventComm.idl>

module event_test { 

  interface PushC : CosEventComm::PushConsumer {
    typedef sequence<any> AnySeq;
    AnySeq get_data();
  };
  interface PullC : CosEventComm::PullConsumer {
    any do_pull();
    any do_try_pull(out boolean has_event);
  };
  
  interface PushS : CosEventComm::PushSupplier {
    void do_push(in any Event);
  };
  interface PullS : CosEventComm::PullSupplier {
    void add_event(in any Event);
  };

}; 
 
#endif


