#! /bin/sh
##
## %CopyrightBegin%
##
## Copyright Ericsson AB 2014-2016. All Rights Reserved.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## %CopyrightEnd%
##
#

## Start the given executable, wait for stop command,
## stop the running executable and wait for exit.

die () {
    r=$?
    echo "$0:" "$*" 1>&2
    exit $r
}

test -x "$1" || die "Not Executable: $1"

# Redirect stdin to make sure the stop command is read by us below
# and does not go to the executable
"$@" 0< /dev/null &
PID=$!

# Wait for stop command
while read LINE; do
    case :"$LINE" in
	:"stop")
	    break;;
    esac
done

kill $PID
wait $PID
