#! /bin/sh
##
## %CopyrightBegin%
##
## Copyright Ericsson AB 2014-2014. All Rights Reserved.
##
## The contents of this file are subject to the Erlang Public License,
## Version 1.1, (the "License"); you may not use this file except in
## compliance with the License. You should have received a copy of the
## Erlang Public License along with this software. If not, it can be
## retrieved online at http://www.erlang.org/.
##
## Software distributed under the License is distributed on an "AS IS"
## basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
## the License for the specific language governing rights and limitations
## under the License.
##
## %CopyrightEnd%
##
#

## Start the given executable, wait for stop command,
## stop the running executable and wait for exit.

die () {
    r=$?
    echo "$0:" "$*" 1>&2
    exit $r
}

test -x "$1" || die "Not Executable: $1"

# Redirect stdin to make sure the stop command is read by us below
# and does not go to the executable
"$@" 0< /dev/null &
PID=$!

# Wait for stop command
while read LINE; do
    case :"$LINE" in
	:"stop")
	    break;;
    esac
done

kill $PID
wait $PID
