
// %CopyrightBegin%
// 
// Copyright Ericsson AB 1998-2016. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// %CopyrightEnd%

// Normal pragmas
 
module M1 {
  
  typedef long T1;
 
  typedef long T2;
 
#pragma ID T2 "DCE:d62207a2-011e-11ce-88b4-0800090b5d3e:3"
 
};
 
 
#pragma prefix "P1"
 
module M2 {
 
  module M3 {

#pragma prefix "P2"
 
    interface I1 {
      void Op( in short b,
                out short c);
    };
    typedef long T3;
  };
  
  
  typedef long T4;
  
#pragma version T4 2.4
 
};
 
 
 
/*
 
  Specified types with the following scoped names 
  and RepositoryIds
 
  ::M1::T1     IDL:M1/T1:1.0
  
  ::M1::T2     DCE:d62207a2-011e-11ce-88b4-0800090b5d3e:3   
  
  ::M2::M3::T3 IDL:P2/T3:1.0
  
  ::M2::T4     IDL:P1/M2/T4:2.4

*/
 







