

// %CopyrightBegin%
// 
// Copyright Ericsson AB 1998-2010. All Rights Reserved.
// 
// The contents of this file are subject to the Erlang Public License,
// Version 1.1, (the "License"); you may not use this file except in
// compliance with the License. You should have received a copy of the
// Erlang Public License along with this software. If not, it can be
// retrieved online at http://www.erlang.org/.
// 
// Software distributed under the License is distributed on an "AS IS"
// basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
// the License for the specific language governing rights and limitations
// under the License.
// 
// %CopyrightEnd%
// Bad pragma IDs
 
// Completelly bad id
module M1 {
  
  typedef long T1;
 
  typedef long T2;
 
#pragma ID T2 "CompletelyBadId"
 
};


// Bad id, should start with DCE
module M2 {
  
  typedef long T1;
 
  typedef long T2;
 
#pragma ID T2 "BAD:d62207a2-011e-11ce-88b4-0800090b5d3e:3"
 
};
 

// Bad version in ID : not a short number
module M3 {
  
  typedef long T1;
 
  typedef long T2;
 
#pragma ID T2 "DCE:d62207a2-011e-11ce-88b4-0800090b5d3e:ABCD"
 
};

 
 


















