#!/usr/bin/env perl 
#
# %CopyrightBegin%
# 
# Copyright Ericsson AB 1999-2009. All Rights Reserved.
# 
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# %CopyrightEnd%
#
use strict;

# Create the file erl_version.h
#
# Usage:
#    make_version [ -o outputfile ] version architecture
#
# Output goes to ./erl_version.h (or to "outputfile" if specified)
#

my $time_str   = localtime;
my $outputfile = "erl_version.h";

@ARGV or die "No arguments given to 'make_version'";

if ($ARGV[0] eq '-o') {
  shift;			# Remove -o
  $outputfile = shift;
  defined $outputfile or die "No output file specified";
}

my $release = shift;
defined $release or die "No release specified";

my $version = shift;
defined $version or die "No version name specified";

my $architecture = shift;
defined $architecture or die "No architecture specified";
$architecture =~ s&^.*[/\\]&&;	# Remove directory part if any

open(FILE, ">$outputfile") or die "Can't create $outputfile: $!";

print FILE <<EOF;
/* This file was created by 'make_version' -- don't modify. */
#define ERLANG_OTP_RELEASE "$release"
#define ERLANG_VERSION "$version"
#define ERLANG_COMPILE_DATE "$time_str"
#define ERLANG_ARCHITECTURE "$architecture"
EOF

close(FILE);

exit(0);
