# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2008-2012. All Rights Reserved.
# 
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# %CopyrightEnd%
# 

CC = @CC@
CFLAGS = @ERTS_CFLAGS@
LIBS = @ERTS_LIBS@
CP=cp
CHMOD=chmod

ERLX_T_CFLAGS = -Wall $(ERLX_DEFS) $(CFLAGS) @DEFS@

GCC = .@DS@gccifier -CC"$(CC)"

PROGS = erlexec_tests@exe@

all: $(PROGS)

@IFEQ@ (@cross@, yes)
gccifier@exe@:
	$(CP) ..@DS@utils@DS@gccifier.sh gccifier@exe@
	$(CHMOD) a+x gccifier@exe@
@ELSE@
gccifier@exe@: ..@DS@utils@DS@gccifier.c
	$(CC) $(CFLAGS) -o gccifier@exe@ ..@DS@utils@DS@gccifier.c $(LIBS)
@ENDIF@

erlexec_tests@exe@: gccifier@exe@ erlexec_tests.c
	$(GCC) $(ERLX_T_CFLAGS) -o erlexec_tests@exe@ erlexec_tests.c

