# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2008-2016. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
# 

CC = @CC@
CFLAGS = @ERTS_CFLAGS@
LIBS = @ERTS_LIBS@
CP=cp
CHMOD=chmod

ERLX_T_CFLAGS = -Wall $(ERLX_DEFS) $(CFLAGS) @DEFS@

GCC = .@DS@gccifier -CC"$(CC)"

PROGS = erlexec_tests@exe@

all: $(PROGS)

@IFEQ@ (@cross@, yes)
gccifier@exe@:
	$(CP) ..@DS@utils@DS@gccifier.sh gccifier@exe@
	$(CHMOD) a+x gccifier@exe@
@ELSE@
gccifier@exe@: ..@DS@utils@DS@gccifier.c
	$(CC) $(CFLAGS) -o gccifier@exe@ ..@DS@utils@DS@gccifier.c $(LIBS)
@ENDIF@

erlexec_tests@exe@: gccifier@exe@ erlexec_tests.c
	$(GCC) $(ERLX_T_CFLAGS) -o erlexec_tests@exe@ erlexec_tests.c

