#
# %CopyrightBegin%
#
# Copyright Ericsson AB 2000-2016. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#

include @erl_interface_mk_include@

CC0 = @CC@
CC = ..@DS@all_SUITE_data@DS@gccifier@exe@ -CC"$(CC0)"
LD = @LD@
LIBERL = @erl_interface_lib@
LIBEI = @erl_interface_eilib@
LIBFLAGS = ../all_SUITE_data/ei_runner@obj@ \
	$(LIBEI) @LIBS@ @erl_interface_sock_libs@ \
	@erl_interface_threadlib@
CFLAGS = @EI_CFLAGS@ $(THR_DEFS) -I@erl_interface_include@ -I../all_SUITE_data
EI_GLOBAL_OBJS = ei_global_test@obj@ ei_global_test_decl@obj@

all: ei_global_test@exe@

clean:
	$(RM) $(EI_GLOBAL_OBJS)
	$(RM) ei_global_test@exe@

ei_global_test@exe@: $(EI_GLOBAL_OBJS) $(LIBEI)
	$(LD) @CROSSLDFLAGS@ -o $@ $(EI_GLOBAL_OBJS) \
	../all_SUITE_data/my_ussi@obj@ $(LIBFLAGS)
