## %CopyrightBegin%
##
## SPDX-License-Identifier: Apache-2.0
##
## Copyright Ericsson AB 2025. All Rights Reserved.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## %CopyrightEnd%

[build_info]
apps = [
    "lib/*",
    {"name" = "erts", "dir" = "erts/preloaded", "src_dirs" = ["src"], "include_dirs" = ["../../lib/kernel/src", "../../lib/kernel/include"]},
    {"name" = "wx", "dir" = "lib/wx", "src_dirs" = ["src", "gen"], "include_dirs" = ["include"]},
    {"name" = "inets", "dir" = "lib/inets", "src_dirs" = ["src"], "include_dirs" = ["include", "src/inets_app", "src/http_lib"]},
    {"name" = "common_test", "dir" = "lib/common_test", "src_dirs" = ["src", "test_server"], "include_dirs" = ["include", "../snmp/include", "../kernel/include"]},
    # Due to some Erlang/OTP bootstrapping issues, `stdlib` modules such as `gen_server` includes headers from the kernel application
    # using a simple `-include` directive, causing ELP to fail resolving those inclusions.
    # Include kernel as an `include_dir` for `stdlib` to solve the issue
    {"name" = "stdlib", "dir" = "lib/stdlib", "src_dirs" = ["src"], "include_dirs" = ["include", "../kernel/include"]},
    {"name" = "dialyzer", "dir" = "lib/dialyzer", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "macros" = {"VSN" = "DEFAULT_VSN"}},
    {"name" = "snmp", "dir" = "lib/snmp", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "src/misc", "src/compile", "src/app"], "macros" = {"default_verbosity"="silence", "version"="version"}},
    {"name" = "sasl", "dir" = "lib/sasl", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["../stdlib/include"]},
    {"name" = "compiler", "dir" = "lib/compiler", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = [ "../stdlib/include"], "macros" = {"COMPILER_VSN"="COMPILER_VSN"}},
    {"name" = "parsetools", "dir" = "lib/parsetools", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["../stdlib/include"]},
    {"name" = "eldap", "dir" = "lib/eldap", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "ebin"]},
    {"name" = "observer", "dir" = "lib/observer", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "../et/include"]},
    ]
deps = []
