#
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2003-2016. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
#
include @erl_interface_mk_include@

CC0 = @CC@
CC = .@DS@gccifier@exe@ -CC"$(CC0)"
CFLAGS0 = @CFLAGS@ -I@erl_interface_include@
CFLAGS = @EI_CFLAGS@ $(THR_DEFS) -I@erl_interface_include@
EI_COMMON_OBJS = runner@obj@ ei_runner@obj@
ALL_OBJS = gccifier@exe@ $(EI_COMMON_OBJS)

CP=cp
CHMOD=chmod

all: $(ALL_OBJS)

$(EI_COMMON_OBJS): gccifier@exe@

@IFEQ@ (@cross@, yes)
gccifier@exe@:
	$(CP) gccifier.sh gccifier@exe@
	$(CHMOD) a+x gccifier@exe@
@ELSE@
gccifier@exe@: gccifier.c
	$(CC0) $(CFLAGS0) -o gccifier@exe@ gccifier.c
@ENDIF@

clean:
	$(RM) $(EI_COMMON_OBJS)
	$(RM) init_tc.beam
	$(RM) gccifier@exe@
