#
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2003-2011. All Rights Reserved.
# 
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# %CopyrightEnd%
#
include @erl_interface_mk_include@@DS@eidefs.mk

CC0 = @CC@
CC = .@DS@gccifier@exe@ -CC"$(CC0)"
CFLAGS0 = @CFLAGS@ -I@erl_interface_include@
CFLAGS = @EI_CFLAGS@ $(THR_DEFS) -I@erl_interface_include@
EI_COMMON_OBJS = runner@obj@ ei_runner@obj@
ALL_OBJS = gccifier@exe@ $(EI_COMMON_OBJS)

CP=cp
CHMOD=chmod

all: $(ALL_OBJS)

$(EI_COMMON_OBJS): gccifier@exe@

@IFEQ@ (@erl_interface_cross_compile@, true)
gccifier@exe@:
	$(CP) gccifier.sh gccifier@exe@
	$(CHMOD) a+x gccifier@exe@
@ELSE@
gccifier@exe@: gccifier.c
	$(CC0) $(CFLAGS0) -o gccifier@exe@ gccifier.c
@ENDIF@

clean:
	$(RM) $(EI_COMMON_OBJS)
	$(RM) init_tc.beam
	$(RM) gccifier@exe@
