# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2004-2016. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
# 

include @erts_lib_make_ethread@
include @erts_lib_make_internal@

CC = @CC@
CFLAGS = @ERTS_CFLAGS@
LIBS = @ERTS_LIBS@
CP=cp
CHMOD=chmod

ETHR_T_CFLAGS = -Wall $(ETHR_DEFS) $(CFLAGS) @DEFS@ -I@erts_lib_include_internal@ -I@erts_lib_include_internal_generated@
ETHR_T_LIBS = $(LIBS) -L@erts_lib_internal_path@ $(ETHR_LIBS) $(ERTS_INTERNAL_X_LIBS)

GCC = .@DS@gccifier -CC"$(CC)"

PROGS = ethread_tests@exe@

all: $(PROGS)

@IFEQ@ (@cross@, yes)
gccifier@exe@:
	$(CP) ..@DS@utils@DS@gccifier.sh gccifier@exe@
	$(CHMOD) a+x gccifier@exe@
@ELSE@
gccifier@exe@: ..@DS@utils@DS@gccifier.c
	$(CC) $(CFLAGS) -o gccifier@exe@ ..@DS@utils@DS@gccifier.c $(LIBS)
@ENDIF@

ethread_tests@exe@: gccifier@exe@ ethread_tests.c
	$(GCC) $(ETHR_T_CFLAGS) -o ethread_tests@exe@ ethread_tests.c -lerts_internal_r $(ETHR_T_LIBS)

