#!/bin/sh

# 
#  %CopyrightBegin%
#  
#  Copyright Ericsson AB 2019-2019. All Rights Reserved.
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  
#  %CopyrightEnd%
# 

EMU=$ERL_TOP/erts/emulator
EMU_TEST=$EMU/test
ESOCK_TTEST=$EMU_TEST/esock_ttest

#  $1 - async  - boolean()
#  $2 - active - once | boolean()
# [$3 - domain - inet (default) | inet6 | local]
if [ $# -ge 2 ]; then

    async=$1
    active=$2

    if [ $async = true ]; then
	ASYNC="--async"
    else
	ASYNC=
    fi

    ACTIVE="--active $active"

    if [ $# = 3 ]; then
	DOMAIN="--domain $3"
    fi


else
    echo "<ERROR> Missing args: async and active"
    echo ""
    exit 1
fi


$ESOCK_TTEST/esock-ttest --server $DOMAIN $ASYNC --transport sock $ACTIVE

