// Naming Service v1.0 described in CORBAservices: 
// Common Object Services Specification, chapter 3
// OMG IDL for CosNaming Module, p 3-6

#ifndef _COSNAMINGEXT_IDL_ 
#define _COSNAMINGEXT_IDL_


#include<cos_naming.idl>

#pragma prefix "omg.org"

module CosNaming
{
  interface NamingContextExt:NamingContext { 
    
    typedef string StringName; 
    typedef string Address; 
    typedef string URLString;
    
    StringName to_string(in Name n)
      raises(InvalidName); 
    
    Name to_name(in StringName sn) 
      raises(InvalidName); 
    
    exception InvalidAddress{}; 
    
    URLString to_url(in Address addr,in StringName sn) 
      raises(InvalidAddress, InvalidName); 
    
    Object resolve_str(in StringName n) 
      raises(NotFound, CannotProceed, InvalidName); 
  }; 
}; 

#endif//_COSNAMINGEXT_IDL_
