# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2015-2015. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
#

CC = @CC@
LD = @LD@
CFLAGS = @CFLAGS@
CROSSLDFLAGS = @CROSSLDFLAGS@

PROGS = setuid_socket_wrap@exe@

.PHONY: all
@IFEQ@ (@os@, linux-gnu)
all: $(PROGS)
@ELSE@
all:
@ENDIF@

setuid_socket_wrap@exe@: setuid_socket_wrap@obj@
	$(LD) $(CROSSLDFLAGS) -o setuid_socket_wrap setuid_socket_wrap@obj@ @LIBS@

setuid_socket_wrap@obj@: setuid_socket_wrap.c
	$(CC) -c $(CFLAGS) -o setuid_socket_wrap@obj@ setuid_socket_wrap.c
