#
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2003-2012. All Rights Reserved.
# 
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# %CopyrightEnd%
#
#
# Makefile.src for java_client_erl_server test
# Note: This file *must* work for both Unix and Windows
#
# We use both `rm' (Unix) and `del' (Windows) for removing files, but
# with a `-' in front so that the error in not finding `rm' (`del') on
# Windows (Unix) is ignored.
#
# VxWorks? XXX 
#

.SUFFIXES:
.SUFFIXES: .erl .idl .@EMULATOR@ .java


JAVAC = @JAVAC@
ERLC = erlc

# ic variables available from ts: 
#
# ic_libpath: @ic_libpath@
# ic_include_path: @ic_include_path@

IC_INCLUDE_PATH = @ic_include_path@
IC_CLASSPATH = @ic_classpath@

JINTERFACE_CLASSPATH = @jinterface_classpath@

CLASSPATH = .@PS@$(IC_CLASSPATH)@PS@$(JINTERFACE_CLASSPATH)@PS@

GEN_JAVA_FILES = \
	m@DS@_iImplBase.java \
	m@DS@_iStub.java \
	m@DS@i.java m@DS@iHelper.java m@DS@iHolder.java \
	m@DS@s.java m@DS@sHelper.java m@DS@sHolder.java

GEN_HRL_FILES = \
	m.hrl \
	m_i.hrl \
	oe_java_erl_test.hrl

GEN_ERL_FILES = \
	m_i.erl \
	oe_java_erl_test.erl

JAVA_FILES = $(GEN_JAVA_FILES) JavaClient.java
CLASS_FILES = $(JAVA_FILES:.java=.class)
ERL_FILES = $(GEN_ERL_FILES) m_i_impl.erl
EBINS = $(ERL_FILES:.erl=.@EMULATOR@)

@IFEQ@ (@jinterface_classpath@,)
all:
@ELSE@
all: $(CLASS_FILES) $(EBINS)
@ENDIF@

$(GEN_ERL_FILES) $(GEN_HRL_FILES):  java_erl_test.built_erl
$(GEN_JAVA_FILES): java_erl_test.built_java
$(CLASS_FILES): $(GEN_JAVA_FILES)
$(EBINS): $(GEN_ERL_FILES) $(GEN_HRL_FILES)

clean:	
	-rm -f $(GEN_JAVA_FILES) $(CLASS_FILES) \
		$(GEN_ERL_FILES) $(GEN_HRL_FILES) $(EBINS) \
		java_erl_test.built_erl java_erl_test.built_java
	-del /F /Q $(GEN_JAVA_FILES) $(CLASS_FILES) \
		$(GEN_ERL_FILES) $(GEN_HRL_FILES) $(EBINS) \
		java_erl_test.built_erl java_erl_test.built_java

java_erl_test.built_java: java_erl_test.idl
	$(gen_verbose)$(ERLC) -I $(IC_INCLUDE_PATH) "+{be,java}" java_erl_test.idl
	$(V_at)echo done > java_erl_test.built_java

$(CLASS_FILES) : $(JAVA_FILES)
	$(V_JAVAC) -classpath $(CLASSPATH) $(JAVA_FILES)

java_erl_test.built_erl: java_erl_test.idl
	$(gen_verbose)$(ERLC) -I $(IC_INCLUDE_PATH) "+{be,erl_genserv}" java_erl_test.idl
	$(V_at)echo done > java_erl_test.built_erl

.erl.@EMULATOR@:
	$(V_ERLC) -I $(IC_INCLUDE_PATH) $<
