#!/usr/bin/env bash
#
# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2015-2025. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#

# Generate ssh moduli files for the sizes in $moduli

moduli="1024 1536 2048 3072 4096 6144 7168 8192"

# In arg 1: size
# Out: a file "moduli-$1" (for example: $1=2048 -> file "moduli.2048"
function one_modulus() {
    candidates=candidate-$1
    ssh-keygen -G $candidates -b $1
    ssh-keygen -T moduli-$1 -f $candidates
    rm $candidates
}


# Generate in background
for m in $moduli
do
    one_modulus $m &
done

# When all files moduli-* are generated, do:
# cat moduli-* > moduli

