    <section>
      <title>erlang:now/0</title>
      <p>New time functionality and a new time API was introduced. For more information
      see the <seealso marker="erts:time_correction">Time and Time Correction</seealso>
      chapter in the ERTS User's guide and specifically the
      <seealso marker="erts:time_correction#Dos_and_Donts">Dos and Donts</seealso>
      section on how to replace usage of <c>erlang:now/0</c>.</p>
    </section>

    <section>
      <title>httpd_conf module</title>
      <p>
	API functions in the module <c>httpd_conf</c> was deprecated in favor
	of standard modules such as <c>lists</c>, <c>string</c>,
	<c>filelib</c>, and <c>erlang</c>.
      </p>
    </section>
