<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE chapter SYSTEM "chapter.dtd">

<chapter>
  <header>
    <copyright>
      <year>2020</year>
      <holder>Ericsson AB. All Rights Reserved.</holder>
    </copyright>
    <legalnotice>
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.

    </legalnotice>

    <title>Deprecations</title>
    <prepared></prepared>
    <docno></docno>
    <date></date>
    <rev></rev>
    <file>deprecations.xml</file>
  </header>
  <section>
    <title>Introduction</title>
    <p>This document lists all deprecated functionality in
    Erlang/OTP. For more information regarding the strategy regarding
    deprecations see the documentation of <seeguide
    marker="system/system_principles:misc#deprecation">Support,
    Compatibility, Deprecations, and Removal</seeguide>.</p>
  </section>
