    <section>
      <title>-code_path_choice support</title>
      <p>
        This command line option controls if paths given in the command
        line, boot scripts, and the code server should be interpreted as
        is (strict) or relaxed.
      </p>
      <p>
        OTP 26 has changed the default value from <c>relaxed</c> to <c>strict</c>
        and the option is scheduled for removal in OTP 27.
      </p>
    </section>
