    <section>
      <title>Old Crypto API</title>
      <p>The <seealso marker="crypto:new_api#the-old-api">Old API</seealso> will be
      removed as of OTP 24. The support was formally deprecated as of OTP 23.</p>
      <p>For replacement functions see the
      <seealso marker="crypto:new_api#the-new-api">New API</seealso>.</p>
    </section>
    <section>
      <title>pg2</title>
      <p>
	<seealso marker="kernel:pg2">pg2</seealso> is as of
	<seealso marker="deprecations#OTP-23">OTP 23 deprecated</seealso>
	and will be removed in OTP 24.
      </p>
    </section>
    <section>
      <title>Distributed Disk Logs</title>
      <p>
	The distributed
	<seealso marker="kernel:disk_log"><c>disk_log</c></seealso>
	feature is as of
	<seealso marker="deprecations#OTP-23">OTP 23 deprecated</seealso>
	and will be removed in OTP 24.
      </p>
    </section>
