    <section>
      <title>Old Crypto API</title>
      <p>The <seeguide marker="crypto:new_api#the-old-api">Old API</seeguide> will be
      removed as of OTP 24. The support was formally deprecated as of OTP 23.</p>
      <p>For replacement functions see the
      <seeguide marker="crypto:new_api#the-new-api">New API</seeguide>.</p>
    </section>
    <section>
      <title>pg2</title>
      <p>
	<seeerl marker="kernel:pg2">pg2</seeerl> is as of
	<seeguide marker="deprecations#otp-23">OTP 23 deprecated</seeguide>
	and will be removed in OTP 24.
      </p>
    </section>
    <section>
      <title>Distributed Disk Logs</title>
      <p>
	The distributed
	<seeerl marker="kernel:disk_log"><c>disk_log</c></seeerl>
	feature is as of
	<seeguide marker="deprecations#otp-23">OTP 23 deprecated</seeguide>
	and will be removed in OTP 24.
      </p>
    </section>
