#!/bin/sh
#
# Make Postscript header files (frame and crop marks)
#
# From environment: BOOK CSFILE USER BOOKBUILD

DATE=`date`
VIEW=`cleartool pwv -s -set`  
LATEX=`which latex`
DVIPSVSN=`dvips -version`
DVIPS=`which dvips`
DOCBVSN=`docb_transform -version`
DOCB=`which docb_transform`
for marks in frame crop; do
    sed -e "s/@DATE@/$DATE/g" \
	-e "s/@BOOK@/$BOOK/g" \
	-e "s/@MARKS@/$marks/g" \
	-e "s;@CSFILE@;$CSFILE;g" \
	-e "s/@VIEW@/$VIEW/g" \
	-e "s/@USER@/$USER/g" \
	-e "s;@LATEX@;$LATEX;g" \
	-e "s;@DVIPSVSN@;$DVIPSVSN;g" \
	-e "s;@DVIPS@;$DVIPS;g" \
	-e "s/@DOCBVSN@/$DOCBVSN/g" \
	-e "s;@DOCB@;$DOCB;g" \
	-e "s;@BOOKBUILD@;$BOOKBUILD;g" \
	-e "s;@BUILDSCRIPT@;$BUILDSCRIPT;g" \
	    frame_crop.header.src > $marks.header
done

