#
# %CopyrightBegin%
#
# Copyright Ericsson AB 2004-2016. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#

# Makefile.src for java_client_erl_server test
# Note: This file *must* work for both Unix and Windows
#
# We use both `rm' (Unix) and `del' (Windows) for removing files, but
# with a `-' in front so that the error in not finding `rm' (`del') on
# Windows (Unix) is ignored.
#
# VxWorks? XXX
#

.SUFFIXES:
.SUFFIXES: .java


JAVAC = @JAVAC@
ERLC = erlc

JINTERFACE_CLASSPATH = @jinterface_classpath@

CLASSPATH = .@PS@$(JINTERFACE_CLASSPATH)@PS@

JAVA_FILES = echo_server.java connection_server.java
CLASS_FILES = $(JAVA_FILES:.java=.class)

all: $(CLASS_FILES)

clean:
	-rm -f $(CLASS_FILES)
	-del /F /Q $(CLASS_FILES)

$(CLASS_FILES) : $(JAVA_FILES)
	$(JAVAC) -classpath $(CLASSPATH) $(JAVA_FILES)

#
