CC = @CC@
LD = @LD@
CFLAGS = @CFLAGS@ -I@erl_include@ @DEFS@
CROSSLDFLAGS = @CROSSLDFLAGS@

PROGS = cgi_sleep@exe@

all: $(PROGS)

cgi_sleep@exe@: cgi_sleep@obj@
	$(LD) $(CROSSLDFLAGS) -o cgi_sleep cgi_sleep@obj@ @LIBS@

cgi_sleep@obj@: cgi_sleep.c
	$(CC) -c -o cgi_sleep@obj@ $(CFLAGS) cgi_sleep.c
