CC = @CC@
LD = @LD@
CFLAGS = @CFLAGS@ -I@erl_include@ @DEFS@
CROSSLDFLAGS = @CROSSLDFLAGS@

PROGS = cgi_echo@exe@

all: $(PROGS)

cgi_echo@exe@: cgi_echo@obj@
	$(LD) $(CROSSLDFLAGS) -o cgi_echo cgi_echo@obj@ @LIBS@

@IFEQ@ (@CC@, cl -nologo)
cgi_echo@obj@: cgi_echo.c
	$(CC) /c /Focgi_echo@obj@ $(CFLAGS) cgi_echo.c
@ELSE@
cgi_echo@obj@: cgi_echo.c
	$(CC) -c -o cgi_echo@obj@ $(CFLAGS) cgi_echo.c
@ENDIF@	
