EFLAGS=+debug_info

P2B= \
     P2B/a-2.0/ebin/a.beam \
     P2B/a-2.0/ebin/a_sup.beam

LIB= \
     lib/a-1.1/ebin/a.beam \
     lib/a-1.1/ebin/a_sup.beam \
     lib/a-1.0/ebin/a.beam \
     lib/a-1.0/ebin/a_sup.beam \

APP= \
     app1_app2/lib1/app1-1.0/ebin/app1_sup.@EMULATOR@ \
     app1_app2/lib1/app1-1.0/ebin/app1_server.@EMULATOR@ \
     app1_app2/lib1/app1-1.0/ebin/app1.@EMULATOR@ \
     app1_app2/lib1/app2-1.0/ebin/app2_sup.@EMULATOR@ \
     app1_app2/lib1/app2-1.0/ebin/app2_server.@EMULATOR@ \
     app1_app2/lib1/app2-1.0/ebin/app2.@EMULATOR@ \
     app1_app2/lib2/app1-2.0/ebin/app1_sup.@EMULATOR@ \
     app1_app2/lib2/app1-2.0/ebin/app1_server.@EMULATOR@ \
     app1_app2/lib2/app1-2.0/ebin/app1.@EMULATOR@ \
     app1_app2/lib2/app2-1.0/ebin/app2_sup.@EMULATOR@ \
     app1_app2/lib2/app2-1.0/ebin/app2_server.@EMULATOR@ \
     app1_app2/lib2/app2-1.0/ebin/app2.@EMULATOR@

OTP2740=  \
     otp_2740/vsn_atom.@EMULATOR@ \
     otp_2740/vsn_list.@EMULATOR@ \
     otp_2740/vsn_numeric.@EMULATOR@ \
     otp_2740/vsn_tuple.@EMULATOR@ \
     otp_2740/vsn_string.@EMULATOR@

C= \
     c/aa.@EMULATOR@ \
     c/b.@EMULATOR@ \
     c/c_sup.@EMULATOR@
    

all: $(P2B) $(LIB) $(APP) $(OTP2740) $(C)

P2B/a-2.0/ebin/a.@EMULATOR@: P2B/a-2.0/src/a.erl
	erlc $(EFLAGS) -oP2B/a-2.0/ebin P2B/a-2.0/src/a.erl
P2B/a-2.0/ebin/a_sup.@EMULATOR@: P2B/a-2.0/src/a_sup.erl
	erlc $(EFLAGS) -oP2B/a-2.0/ebin P2B/a-2.0/src/a_sup.erl


lib/a-1.0/ebin/a.@EMULATOR@: lib/a-1.0/src/a.erl
	erlc $(EFLAGS) -olib/a-1.0/ebin lib/a-1.0/src/a.erl
lib/a-1.0/ebin/a_sup.@EMULATOR@: lib/a-1.0/src/a_sup.erl
	erlc $(EFLAGS) -olib/a-1.0/ebin lib/a-1.0/src/a_sup.erl


lib/a-1.1/ebin/a.@EMULATOR@: lib/a-1.1/src/a.erl
	erlc $(EFLAGS) -olib/a-1.1/ebin lib/a-1.1/src/a.erl
lib/a-1.1/ebin/a_sup.@EMULATOR@: lib/a-1.1/src/a_sup.erl
	erlc $(EFLAGS) -olib/a-1.1/ebin lib/a-1.1/src/a_sup.erl


app1_app2/lib1/app1-1.0/ebin/app1_sup.@EMULATOR@: app1_app2/lib1/app1-1.0/src/app1_sup.erl
	erlc $(EFLAGS) -oapp1_app2/lib1/app1-1.0/ebin app1_app2/lib1/app1-1.0/src/app1_sup.erl
app1_app2/lib1/app1-1.0/ebin/app1_server.@EMULATOR@: app1_app2/lib1/app1-1.0/src/app1_server.erl
	erlc $(EFLAGS) -oapp1_app2/lib1/app1-1.0/ebin app1_app2/lib1/app1-1.0/src/app1_server.erl
app1_app2/lib1/app1-1.0/ebin/app1.@EMULATOR@: app1_app2/lib1/app1-1.0/src/app1.erl
	erlc $(EFLAGS) -oapp1_app2/lib1/app1-1.0/ebin app1_app2/lib1/app1-1.0/src/app1.erl


app1_app2/lib1/app2-1.0/ebin/app2_sup.@EMULATOR@: app1_app2/lib1/app2-1.0/src/app2_sup.erl
	erlc $(EFLAGS) -oapp1_app2/lib1/app2-1.0/ebin app1_app2/lib1/app2-1.0/src/app2_sup.erl
app1_app2/lib1/app2-1.0/ebin/app2_server.@EMULATOR@: app1_app2/lib1/app2-1.0/src/app2_server.erl
	erlc $(EFLAGS) -oapp1_app2/lib1/app2-1.0/ebin app1_app2/lib1/app2-1.0/src/app2_server.erl
app1_app2/lib1/app2-1.0/ebin/app2.@EMULATOR@: app1_app2/lib1/app2-1.0/src/app2.erl
	erlc $(EFLAGS) -oapp1_app2/lib1/app2-1.0/ebin app1_app2/lib1/app2-1.0/src/app2.erl


app1_app2/lib2/app1-2.0/ebin/app1_sup.@EMULATOR@: app1_app2/lib2/app1-2.0/src/app1_sup.erl
	erlc $(EFLAGS) -oapp1_app2/lib2/app1-2.0/ebin app1_app2/lib2/app1-2.0/src/app1_sup.erl
app1_app2/lib2/app1-2.0/ebin/app1_server.@EMULATOR@: app1_app2/lib2/app1-2.0/src/app1_server.erl
	erlc $(EFLAGS) -oapp1_app2/lib2/app1-2.0/ebin app1_app2/lib2/app1-2.0/src/app1_server.erl
app1_app2/lib2/app1-2.0/ebin/app1.@EMULATOR@: app1_app2/lib2/app1-2.0/src/app1.erl
	erlc $(EFLAGS) -oapp1_app2/lib2/app1-2.0/ebin app1_app2/lib2/app1-2.0/src/app1.erl


app1_app2/lib2/app2-1.0/ebin/app2_sup.@EMULATOR@: app1_app2/lib2/app2-1.0/src/app2_sup.erl
	erlc $(EFLAGS) -oapp1_app2/lib2/app2-1.0/ebin app1_app2/lib2/app2-1.0/src/app2_sup.erl
app1_app2/lib2/app2-1.0/ebin/app2_server.@EMULATOR@: app1_app2/lib2/app2-1.0/src/app2_server.erl
	erlc $(EFLAGS) -oapp1_app2/lib2/app2-1.0/ebin app1_app2/lib2/app2-1.0/src/app2_server.erl
app1_app2/lib2/app2-1.0/ebin/app2.@EMULATOR@: app1_app2/lib2/app2-1.0/src/app2.erl
	erlc $(EFLAGS) -oapp1_app2/lib2/app2-1.0/ebin app1_app2/lib2/app2-1.0/src/app2.erl


otp_2740/vsn_atom.@EMULATOR@: otp_2740/vsn_atom.erl
	erlc $(EFLAGS) -ootp_2740 otp_2740/vsn_atom.erl
otp_2740/vsn_list.@EMULATOR@: otp_2740/vsn_list.erl
	erlc $(EFLAGS) -ootp_2740 otp_2740/vsn_list.erl
otp_2740/vsn_numeric.@EMULATOR@: otp_2740/vsn_numeric.erl
	erlc $(EFLAGS) -ootp_2740 otp_2740/vsn_numeric.erl
otp_2740/vsn_tuple.@EMULATOR@: otp_2740/vsn_tuple.erl
	erlc $(EFLAGS) -ootp_2740 otp_2740/vsn_tuple.erl
otp_2740/vsn_string.@EMULATOR@: otp_2740/vsn_string.erl
	erlc $(EFLAGS) -ootp_2740 otp_2740/vsn_string.erl

c/aa.@EMULATOR@: c/aa.erl
	erlc $(EFLAGS) -oc c/aa.erl
c/b.@EMULATOR@: c/b.erl
	erlc $(EFLAGS) -oc c/b.erl
c/c_sup.@EMULATOR@: c/c_sup.erl
	erlc $(EFLAGS) -oc c/c_sup.erl
