#! /bin/sh
# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2002-2016. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
# 
# Note! This shellscript expects to be run in a cygwin environment,
# it converts erlc command lines to native windows erlc commands, which
# basically means running the command cygpath on whatever is a path...

CMD=""
ECHO_ONLY=false
for x in "$@"; do 
    case "$x" in
	--echo_only)
	    ECHO_ONLY=true;;
	-I/*|-o/*)
	    y=`echo $x | sed 's,^-[Io]\(/.*\),\1,g'`;
	    z=`echo $x | sed 's,^-\([Io]\)\(/.*\),\1,g'`;
	    MPATH=`cygpath -m $y`;
	    CMD="$CMD -$z$MPATH";;
	-pa/*)
	    y=`echo $x | sed 's,^-pa\(/.*\),\1,g'`;
	    MPATH=`cygpath -m $y`;
	    CMD="$CMD -pa $MPATH";;
	/*)
	    MPATH=`cygpath -m $x`;
	    CMD="$CMD \"$MPATH\"";; 
# Needed for  +'{preproc_flags,whatever}'
	+{preproc_flags,*})
	     y=`echo $x | sed 's,^+{preproc_flags\,"\(.*\)"},\1,g'`;
	     z=`eval $0 --echo_only $y`;
	     case "$z" in # Dont "doubledoublequote"
		 \"*\") 
		 CMD="$CMD +'{preproc_flags,$z}'";;
		 *)
		 CMD="$CMD +'{preproc_flags,\"$z\"}'";;
	     esac;;
	*)
	    y=`echo $x | sed 's,",\\\",g'`;
	    CMD="$CMD \"$y\"";;
    esac
done
if [ $ECHO_ONLY = true ]; then
    echo $CMD
else
    eval erlc.exe $CMD
fi
