# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 1997-2016. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
#

include @erl_interface_mk_include@

CC0 = @CC@
CC = ..@DS@all_SUITE_data@DS@gccifier@exe@ -CC"$(CC0)"
LD = @LD@
LIBERL = @erl_interface_lib@
LIBEI = @erl_interface_eilib@
LIBFLAGS = ../all_SUITE_data/runner@obj@ \
	$(LIBERL) $(LIBEI) @erl_interface_sock_libs@ @LIBS@ \
	@erl_interface_threadlib@
CFLAGS = @EI_CFLAGS@ $(THR_DEFS) -I@erl_interface_include@ -I../all_SUITE_data
ETERM_OBJS = eterm_test@obj@ eterm_test_decl@obj@
CNODE_OBJS = cnode@obj@
PRINT_OBJS = print_term@obj@
EXE_FILES  = eterm_test@exe@ print_term@exe@ cnode@exe@

all: $(EXE_FILES)

eterm_test@exe@: $(ETERM_OBJS) $(LIBERL) $(LIBEI)
	$(LD) @CROSSLDFLAGS@ -o $@ $(ETERM_OBJS) $(LIBFLAGS)

cnode@exe@: $(CNODE_OBJS) $(LIBERL) $(LIBEI)
	$(LD) @CROSSLDFLAGS@ -o $@ $(CNODE_OBJS) $(LIBFLAGS)

print_term@exe@: print_term@obj@ $(LIBERL) $(LIBEI)
	$(LD) @CROSSLDFLAGS@ -o $@ $(PRINT_OBJS) $(LIBFLAGS)

clean:
	$(RM) $(ETERM_OBJS) $(CNODE_OBJS) $(PRINT_OBJS)
	$(RM) $(EXE_FILES)
