#
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2004-2009. All Rights Reserved.
# 
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# %CopyrightEnd%
#

include @erl_interface_mk_include@@DS@eidefs.mk

CC0 = @CC@
CC = ..@DS@all_SUITE_data@DS@gccifier@exe@ -CC"$(CC0)"
LD = @LD@
LIBPATH = @erl_interface_libpath@
LIBEI = $(LIBPATH)/@erl_interface_eilib@
LIBFLAGS = ../all_SUITE_data/ei_runner@obj@ \
	$(LIBEI) @LIBS@ @erl_interface_sock_libs@ \
	@erl_interface_threadlib@
CFLAGS = @EI_CFLAGS@ $(THR_DEFS) -I@erl_interface_include@ -I../all_SUITE_data
EI_ENCODE_OBJS = ei_encode_test@obj@ ei_encode_test_decl@obj@

all: ei_encode_test@exe@

clean:
	$(RM) $(EI_ENCODE_OBJS)
	$(RM) ei_encode_test@exe@

ei_encode_test@exe@: $(EI_ENCODE_OBJS) $(LIBEI)
	$(LD) @CROSSLDFLAGS@ -o $@ $(EI_ENCODE_OBJS) $(LIBFLAGS)


