#
# %CopyrightBegin%
#
# Copyright Ericsson AB 2004-2010. All Rights Reserved.
#
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# %CopyrightEnd%
#

# Note: This file *must* work for both Unix and Windows
#
# We use both `rm' (Unix) and `del' (Windows) for removing files, but
# with a `-' in front so that the error in not finding `rm' (`del') on
# Windows (Unix) is ignored.
#
# VxWorks? XXX
#

.SUFFIXES:
.SUFFIXES: .java


JAVAC = @JAVAC@
ERLC = erlc

JINTERFACE_CLASSPATH = @jinterface_classpath@

CLASSPATH = .@PS@$(JINTERFACE_CLASSPATH)@PS@

JAVA_FILES = \
	Nodename.java \
	RegisterAndWhereis.java \
	GetNames.java \
	BooleanAtom.java \
	NodePing.java \
	MboxPing.java \
	MboxSendReceive.java \
	MboxLinkUnlink.java \
	NodeStatusHandler.java

CLASS_FILES = $(JAVA_FILES:.java=.class)

all: $(CLASS_FILES)

clean:
	-rm -f $(CLASS_FILES)
	-del /F /Q $(CLASS_FILES)

$(CLASS_FILES) : $(JAVA_FILES)
	$(JAVAC) -classpath $(CLASSPATH) $(JAVA_FILES)

#
