name: Build Base Image
description: 'Builds the base testing image (using cache if possible)'

inputs:
  BASE_BRANCH:
    required: true
  TYPE:
    default: '64-bit'
  BUILD_IMAGE:
    default: true
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'

runs:
    using: composite
    steps:
      - name: Cleanup GH Runner
        shell: bash
        run: .github/scripts/cleanup_gh_runner.sh

      ## Make sure to invalidate cache once a day so that we don't end up
      ## with a stale cache when kerl och apt-get upgrade updates things
      - name: Get current Erlang releases
        id: date
        shell: bash
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache BASE image
        uses: actions/cache@v4.1.1
        if: inputs.TYPE == '64-bit' || inputs.TYPE == 'clang'
        with:
            path: otp_docker_base.tar
            key: ${{ runner.os }}-${{ hashFiles('.github/dockerfiles/Dockerfile.ubuntu-base', '.github/scripts/build-base-image.sh') }}-${{ steps.date.outputs.date }}-${{ hashFiles('OTP_VERSION') }}

      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ inputs.github_token }}

      - name: Build BASE image
        shell: bash
        run: .github/scripts/build-base-image.sh "${{ inputs.BASE_BRANCH }}" "${{ inputs.TYPE }}"

      - name: Cache pre-built src
        if: inputs.BUILD_IMAGE == 'true'
        uses: actions/cache@v4.1.1
        with:
            path: otp_src.tar.gz
            key: prebuilt-src-${{ github.ref_name }}-${{ github.sha }}
      - name: Cache pre-built binaries
        if: inputs.BUILD_IMAGE == 'true'
        uses: actions/cache@v4.1.1
        with:
            path: otp_cache.tar.gz
            key: prebuilt-cache-${{ inputs.TYPE }}-${{ github.ref_name }}-${{ github.sha }}
      - name: Build image
        if: inputs.BUILD_IMAGE == 'true'
        shell: bash -eo pipefail {0}
        run: |
          .github/scripts/restore-from-prebuilt.sh `pwd` .github/otp.tar.gz
          rm -f otp_{src,cache}.tar.gz
          docker build --tag otp \
            --build-arg MAKEFLAGS=-j$(($(nproc) + 2)) \
            --file ".github/dockerfiles/Dockerfile.${{ inputs.TYPE }}" \
            .github/
