#
# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 1996-2026. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#

CC = @CC@
LD = @LD@
CFLAGS = @CFLAGS@ @DEFS@
CROSSLDFLAGS = @CROSSLDFLAGS@

MISC_DRVS =		outputv_drv@dll@ \
			timer_drv@dll@ \
			queue_drv@dll@ \
			io_ready_exit_drv@dll@ \
			chkio_drv@dll@ \
			monitor_drv@dll@ \
			ioq_exit_drv@dll@ \
			peek_non_existing_queue_drv@dll@ \
			otp_6879_drv@dll@ \
			caller_drv@dll@ \
			many_events_drv@dll@ \
			missing_callback_drv@dll@ \
			thr_alloc_drv@dll@ \
			otp_9302_drv@dll@ \
			thr_free_drv@dll@ \
			async_blast_drv@dll@ \
			thr_msg_blast_drv@dll@ \
			consume_timeslice_drv@dll@ \
			env_drv@dll@ \
			erl_errno_id_drv@dll@

SYS_INFO_DRVS = 	sys_info_base_drv@dll@ \
			sys_info_prev_drv@dll@ \
			sys_info_curr_drv@dll@

VSN_MISMATCH_DRVS =	zero_extended_marker_garb_drv@dll@ \
			invalid_extended_marker_drv@dll@ \
			larger_major_vsn_drv@dll@ \
			larger_minor_vsn_drv@dll@ \
			smaller_major_vsn_drv@dll@ \
			smaller_minor_vsn_drv@dll@

PROGS = 		lots_of_fds_used_wrapper@exe@

all: $(MISC_DRVS) $(SYS_INFO_DRVS) $(VSN_MISMATCH_DRVS) $(PROGS)

lots_of_fds_used_wrapper@exe@: lots_of_fds_used_wrapper@obj@
	$(LD) $(CROSSLDFLAGS) -o lots_of_fds_used_wrapper lots_of_fds_used_wrapper@obj@ @LIBS@

lots_of_fds_used_wrapper@obj@: lots_of_fds_used_wrapper.c
	$(CC) -c -o lots_of_fds_used_wrapper@obj@ $(CFLAGS) lots_of_fds_used_wrapper.c

@SHLIB_RULES@

$(SYS_INFO_DRVS): sys_info_drv_impl.h sys_info_drv_impl.c
$(VSN_MISMATCH_DRVS): vsn_mismatch_drv_impl.c

