#! /bin/sh -f
# %CopyrightBegin%
#
# Copyright Ericsson AB 2009-2010. All Rights Reserved.
#
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# %CopyrightEnd%

# Usage: rtt [-cerl] <args to erlang startup script>

emu=erl
while [ $# -gt 0 ]; do
    case "$1" in
	"-cerl")
	    shift
	    emu="$ERL_TOP/bin/cerl"
	    ;;
	*)
	    break
	    ;;
    esac
done

log=test_log_$$
latest=test_log_latest
args=${1+"$@"}

erlcmd="$emu -sname test_server -smp -pa ../../reltool/ebin $p $args -reltool_test_verbose true -reltool_test_timeout"

echo "Give the following command in order to see the outcome:"
echo ""
echo "	less $log"

rm "$latest" 2>/dev/null
ln -s "$log" "$latest"
touch "$log"

ostype=`uname -s`
if [ "$ostype" = "SunOS" ] ; then 
  /usr/openwin/bin/xterm -T "Testing reltool" -l -lf "$log" -e $erlcmd &
else
  xterm -T "Testing reltool" -e script -f -c "$erlcmd" "$log"  &
fi

tail -f "$log" | egrep 'Eval|<ERROR>|NYI'
