
NIF_LIBS = nif_SUITE.1@dll@ \
           nif_mod.1@dll@ \
           nif_mod.2@dll@ \
           nif_mod.3@dll@ \
	   nif_mod.1.2_0@dll@ \
	   nif_mod.2.2_0@dll@ \
	   nif_mod.3.2_0@dll@ \
	   nif_mod.1.2_4@dll@ \
	   nif_mod.2.2_4@dll@ \
	   nif_mod.3.2_4@dll@

all: $(NIF_LIBS) basic@dll@ rwlock@dll@ tsd@dll@ echo_drv@dll@

@SHLIB_RULES@

$(NIF_LIBS): nif_SUITE.c nif_mod.c nif_mod.h

basic@dll@: tester.c testcase_driver.h

rwlock@dll@: tester.c testcase_driver.h

tsd@dll@: tester.c testcase_driver.h

DRIVER_DIR = ../erl_drv_thread_SUITE_data

basic.c rwlock.c tsd.c: $(DRIVER_DIR)/$@
	cat head.txt > $@
	cat $(DRIVER_DIR)/$@ | sed -e 's/erl_drv_/enif_/g' -e 's/driver_/enif_/g' -e 's/ErlDrv/ErlNif/g' >> $@
	cat tail.txt >> $@
