# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2005-2012. All Rights Reserved.
# 
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# %CopyrightEnd%
# 

include @erts_lib_make_ethread@

CC = @CC@
CFLAGST = @ERTS_CFLAGS@
LIBST = @ERTS_LIBS@
CFLAGSF = @CFLAGS@
LIBSF = @LIBS@
CP=cp
CHMOD=chmod

COMMON_CFLAGS = -Wall @DEFS@ -I@erts_lib_include_internal@ -I@erts_lib_include_internal_generated@

EPTF_CFLAGS = $(CFLAGSF) $(COMMON_CFLAGS)
EPTF_LIBS = -L@erts_lib_internal_path@ -lerts_internal@type_marker@ $(LIBSF)

EPTT_CFLAGS = -DTHREAD_SAFE $(ETHR_DEFS) $(CFLAGST) $(COMMON_CFLAGS)
EPTT_LIBS = -L@erts_lib_internal_path@ -lerts_internal_r@type_marker@ $(ETHR_LIBS) $(LIBST)

GCC = .@DS@gccifier -CC"$(CC)"

PROGS = erl_print_tests.true@exe@ erl_print_tests.false@exe@

all: $(PROGS)

@IFEQ@ (@cross@, yes)
gccifier@exe@:
	$(CP) ..@DS@utils@DS@gccifier.sh gccifier@exe@
	$(CHMOD) a+x gccifier@exe@
@ELSE@
gccifier@exe@: ..@DS@utils@DS@gccifier.c
	$(CC) $(CFLAGST) -o gccifier@exe@ ..@DS@utils@DS@gccifier.c $(LIBST)
@ENDIF@

erl_print_tests.false@exe@: gccifier@exe@ erl_print_tests.c
	$(GCC) $(EPTF_CFLAGS) -o erl_print_tests.false@exe@ erl_print_tests.c $(EPTF_LIBS)

erl_print_tests.true@exe@: gccifier@exe@ erl_print_tests.c
	$(GCC) $(EPTT_CFLAGS) -o erl_print_tests.true@exe@ erl_print_tests.c $(EPTT_LIBS)
