#
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2021. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
#

include @erl_interface_mk_include@

CC = @CC@
LD = @LD@

CFLAGS = @EI_CFLAGS@ $(THR_DEFS) -I@erl_interface_include@ 

LIBEI = @erl_interface_eilib@
LIBFLAGS = $(LIBEI) @LIBS@ @erl_interface_sock_libs@ @erl_interface_threadlib@

all: fwd_node@exe@

fwd_node@exe@: fwd_node@obj@ $(LIBEI)
	$(LD) @CROSSLDFLAGS@ -o $@ fwd_node@obj@ $(LIBFLAGS)

clean:
	$(RM) fwd_node@obj@
	$(RM) fwd_node@exe@

