%%
%% %CopyrightBegin%
%% 
%% Copyright Ericsson AB 1997-2016. All Rights Reserved.
%% 
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%     http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.
%% 
%% %CopyrightEnd%
%%
%%
%% Generated by the Erlang ASN.1 compiler version:0.8.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET in module External

-record('XSeq1',{bool1, int1, seq1}).
-record('XSeqIn',{boolIn, intIn}).
-record('XSet1',{bool1, int1, set1}).
-record('XSetIn',{boolIn, intIn}).
-record('XSetExt1',{asn1_EXT}).
-record('XSetExt2',{bool, int, asn1_EXT}).
-record('XSetExt3',{asn1_EXT, bool, int}).
-record('XSetExt4',{bool, asn1_EXT, int}).
-record('XSeqExt1',{asn1_EXT}).
-record('XSeqExt2',{bool, int, asn1_EXT}).
-record('XSeqExt3',{asn1_EXT, bool, int}).
-record('XSeqExt4',{bool, asn1_EXT, int}).
-record('XSetNT',{os, bool}).
-record('XSetImp',{os, bool}).
-record('XSetExp',{os, bool}).
-record('XSeqNT',{os, bool}).
-record('XSeqImp',{os, bool}).
-record('XSeqExp',{os, bool}).

