#!/bin/sh

# 
#  %CopyrightBegin%
#  
#  Copyright Ericsson AB 2019-2019. All Rights Reserved.
#  
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  
#  %CopyrightEnd%
# 

EMU=$ERL_TOP/erts/emulator
EMU_TEST=$EMU/test
ESOCK_TTEST=$EMU_TEST/esock_ttest

RUNTIME=30

MSGID=$1
SERVER_ADDR=$2
SERVER_PORT=$3

# ---------------------------------------------------------------------------

ITERATIONS="\
    gen  false  $MSGID
    gen  true   $MSGID
    gen  once   $MSGID
    sock false  $MSGID
    sock true   $MSGID
    sock once   $MSGID"

#     gen  false  2
#     gen  true   2
#     gen  once   2
#     sock false  2
#     sock true   2
#     sock once   2
#     gen  false  3
#     gen  true   3
#     gen  once   3
#     sock false  3
#     sock true   3
#     sock once   3
# 

# ---------------------------------------------------------------------------

echo "$ITERATIONS" |
  while read TRANSPORT ACTIVE MSG_ID; do

      echo ""
      echo "=========== transport = $TRANSPORT, active = $ACTIVE, msg-id = $MSG_ID ==========="
      # The /dev/null at the end is necessary because erlang "does things" with stdin
      # and this case would cause the 'while read' to "fail" so that we only would
      # loop one time
      $ESOCK_TTEST/esock-ttest --client --transport $TRANSPORT --active $ACTIVE --msg-id $MSG_ID --scon $SERVER_ADDR:$SERVER_PORT --runtime $RUNTIME </dev/null
      echo ""

  done


