# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2010-2013. All Rights Reserved.
# 
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# %CopyrightEnd%
# 

include @erts_lib_include_internal_generated@@DS@ethread.mk
include @erts_lib_include_internal_generated@@DS@erts_internal.mk

NIF_LIBS = mtx_SUITE@dll@

SHLIB_EXTRA_CFLAGS =  $(ETHR_DEFS) -I@erts_lib_include_internal@ -I@erts_lib_include_internal_generated@
LIBS = @ERTS_LIBS@

all: $(NIF_LIBS)

mtx_SUITE.c: force_rebuild
	touch mtx_SUITE.c

force_rebuild:
	echo "Force rebuild to compensate for emulator type dependencies"


@SHLIB_RULES@
