# 
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2010-2016. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
# 

include @erts_lib_make_ethread@
include @erts_lib_make_internal@

NIF_LIBS = mtx_SUITE@dll@

SHLIB_EXTRA_CFLAGS =  $(ETHR_DEFS) -I@erts_lib_include_internal@ -I@erts_lib_include_internal_generated@
LIBS = @ERTS_LIBS@

all: $(NIF_LIBS)

mtx_SUITE.c: force_rebuild
	touch mtx_SUITE.c

force_rebuild:
	echo "Force rebuild to compensate for emulator type dependencies"


@SHLIB_RULES@
