

// %CopyrightBegin%
// 
// Copyright Ericsson AB 1998-2016. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// %CopyrightEnd%
#define 8
#define 
#define a
#define _a
#define b dfs
#define 9 fdas
#define a8
#define A
#define (c) fadfas
#define )c) fadfas
#define % c) fadfas
#define d(p) kfdsa
#define e(p) sinus(p)
#warning warning line
#define w%er percent
#define q() no_para
#warning warning line
#undef
#undef 8
#undef a
#undef b
#undef _a d(kk)

