#ifndef _CORBA_IDL
#define _CORBA_IDL

#pragma prefix "omg.org"

//******************************************************************
//
//Policy Object:
//
//******************************************************************

module CORBA {

  // Policy typedefs
  typedef unsigned long PolicyType;
  typedef string Identifier;
  typedef string ScopedName;
  typedef string RepositoryId;
 
};

#endif
