#ifndef _ORBER_IFR_IDL
#define _ORBER_IFR_IDL

module OrberApp
{
  interface IFR {
    string get_absolute_name(in string TypeID);
    CORBA::TypeCode get_user_exception_type(in string TypeID);
  };
};

#endif
