-- %CopyrightBegin%
-- 
-- Copyright Notice
-- 
--    Copyright (c) 1991 IETF Trust and the persons identified as the
--    document authors.  All rights reserved.
-- 
--    This document is subject to BCP 78 and the IETF Trust's Legal
--    Provisions Relating to IETF Documents
--    (http://trustee.ietf.org/license-info) in effect on the date of
--    publication of this document.  Please review these documents
--    carefully, as they describe your rights and restrictions with respect
--    to this document.
-- 
-- %CopyrightEnd%

RFC-1215 DEFINITIONS ::= BEGIN

IMPORTS
        ObjectName
    FROM RFC1155-SMI;
 
TRAP-TYPE MACRO ::=
BEGIN
    TYPE NOTATION ::=
                  "ENTERPRISE" value (enterprise OBJECT IDENTIFIER)
                  VarPart
                  DescrPart
                  ReferPart
    VALUE NOTATION ::=
                  value (VALUE INTEGER)
    VarPart ::=
                  "VARIABLES" "{" VarTypes "}"
                | empty
    VarTypes ::=
                  VarType | VarTypes "," VarType
    VarType ::=
                  value (vartype ObjectName)
    DescrPart ::=
                 "DESCRIPTION" value (description DisplayString)
               | empty
    ReferPart ::=
                 "REFERENCE" value (reference DisplayString)
               | empty
END
 
