#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage $0 32|64 [command]"
    exit 1
fi

ARCH="$1"

git archive --format=tar.gz --prefix=otp/ HEAD >otp.tar.gz

docker build -t otp --file scripts/Dockerfile.$ARCH .
docker run --volume="$PWD/logs:/buildroot/otp/logs" -i --rm otp $2
