#!/bin/bash

# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2020-2025. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

set -e

GIT_TAG="$1"
ERL_TOP=${ERL_TOP:-$PWD}

OTP_META_FILE=$ERL_TOP/artifacts/${GIT_TAG}.0-bundle.txt
OTP_FILE=$ERL_TOP/artifacts/${GIT_TAG}.0-bundle.tar.gz

REPOSITORIES="otp,$GIT_TAG corba,.*"

if [ ! -d $ERL_TOP/artifacts ]; then
    mkdir $ERL_TOP/artifacts
fi

mkdir bundle

## Turn off * expansion, needed for the .* regexp to work
set -f

for repo in $REPOSITORIES; do
    OLD_IFS=$IFS
    IFS=','
    set -- $repo
    IFS=$OLD_IFS
    cd $ERL_TOP/bundle/
    git clone https://github.com/erlang/$1 $1
    cd $1
    echo $1 $2
    TAG=`git tag -l | grep -P "^$2$" | sort -V | tail -1`
    git checkout $TAG
    SHA=`git rev-parse --verify HEAD`
    rm -rf .git
    echo "$1 $TAG $SHA" >> $OTP_META_FILE
done

## Turn on * expansion
set +f

cd $ERL_TOP/bundle/
tar czf $OTP_FILE *

exit 0
