#!/bin/bash
set -ev

if [ -d $ERL_TOP/release/tests/test_server ]; then
    cd $ERL_TOP/release/tests/test_server
elif [ -d test_server ]; then
    cd test_server
else
    echo "Could not find tests"
    exit 1;
fi

erl -noshell -s ts install -s ts smoke_test batch -s init stop

if grep -q '=failed *[1-9]' ct_run.test_server@*/*/run.*/suite.log; then
    echo "One or more tests failed."
    exit 1
fi

rm -rf ct_run.test_server@*
