#!/bin/bash

set -e
set -x

$ERL_TOP/bin/dialyzer --build_plt --apps asn1 compiler crypto dialyzer edoc erts et ftp hipe inets kernel mnesia observer public_key runtime_tools snmp ssh ssl stdlib syntax_tools tftp wx xmerl --statistics
$ERL_TOP/bin/dialyzer -n -Wunknown -Wunmatched_returns --apps compiler erts ftp tftp kernel stdlib asn1 crypto dialyzer hipe parsetools public_key runtime_tools sasl tools --statistics
$ERL_TOP/bin/dialyzer -n --apps common_test debugger edoc ftp inets mnesia observer ssh ssl syntax_tools tftp wx xmerl --statistics

# In travis we don't dialyze everything as it takes too much time
if [ "X$TRAVIS" != "Xtrue" ]; then
    $ERL_TOP/bin/dialyzer -n -Wunknown -Wunmatched_returns --apps eldap erl_docgen et odbc --statistics
    $ERL_TOP/bin/dialyzer -n --apps eunit reltool os_mon --statistics

    # These application are not run always as the currently have dialyzer warnings
    # $ERL_TOP/bin/dialyzer -n --apps diameter megaco snmp --statistics
fi
