#
# %CopyrightBegin%
# 
# Copyright Ericsson AB 2023. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
#

include @erl_interface_mk_include@

CC = @CC@
LD = @LD@
CFLAGS = @CFLAGS@ -I@erl_include@ @DEFS@
CROSSLDFLAGS = @CROSSLDFLAGS@

SHLIB_EXTRA_CFLAGS = @EI_CFLAGS@ -I@erl_interface_include@ 
SHLIB_EXTRA_LDLIBS = @erl_interface_eilib@ @erl_interface_sock_libs@

all: send_term_local_drv@dll@ call_local_drv@dll@

@SHLIB_RULES@
