# Dummy Makefile.src defined to provide backward compatibility for
# applications that use both the new SSL (3.0 or later), and older
# versions of SSL.
#

SSL_LIB_DIR = @ssl_libdir@
TARGET = @target@
SSLEAY_LIB = @SSLEAY_ROOT@/lib

all:
	-echo "Begin dummy make"
	-echo SSL_LIB_DIR = $(SSL_LIB_DIR)
	-echo TARGET = $(TARGET)
	-echo SSLEAY_LIB = $(SSLEAY_LIB)
	-echo SSL_LIB_DIR = $(SSL_LIB_DIR)
	-echo "End dummy make"
