
// %CopyrightBegin%
// 
// Copyright Ericsson AB 1997-2016. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// %CopyrightEnd%
//
// Check that multiply defined identifiers are detected
//

typedef long T1;
typedef long T1;
typedef long T2;
exception T2 {};


//Exceptions
exception Exc1 {};
exception Exc1 {};


// Enums
enum E1 {kalle};
enum E1 {kalle};
enum E2 {kalle, sune, kalle};


// Structs
struct S1 {long a;};
struct S1 {long a;};
struct S2 {long a; short a;};
struct S3 {long a,b; short a;};
struct S4 {long a,a; short a;};


// Constants
const long c1 = 0;
const long c1 = 0;


// Interfaces

interface i1 {};
interface i1 {};

interface i2 {
  attribute long a1;
  attribute long a1;
};

interface i3 {
  attribute long a1, a2;
  attribute long a2;
};

interface i4 {
  attribute long a1, a1;
};

interface i5 {
  long op1();
  long op1();

  long op2(in long a, inout char a);
};


// Unions 

union U1 switch (long) {case 1: long a;};
union U1 switch (long) {case 1: long a;};

union U2 switch (long) {
case 1: long a;
default: char a;
};





