

// %CopyrightBegin%
// 
// Copyright Ericsson AB 1997-2016. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// 
// %CopyrightEnd%

//
// Checks nasty name collisions
//

typedef string T;


#define nasty01 version
#define nasty02 preproc
#define nasty03 pragma
#define nasty04 compile
#define nasty05 if
#define nasty06 receive
#define nasty07 foldr
#define nasty08 length
#define nasty09 ID

interface I1 {
  attribute T nasty01;
  attribute T nasty02;
  attribute T nasty03;
  attribute T nasty04;
  attribute T nasty05;
  attribute T nasty06;
  attribute T nasty07;
  attribute T nasty08;
  attribute T nasty09;
};

interface I2 {
  T nasty01();
  T nasty02();
  T nasty03();
  T nasty04();
  T nasty05();
  T nasty06();
  T nasty07();
  T nasty08();
  T nasty09();
};

