#!/bin/sh
#
# %CopyrightBegin%
#
# Copyright Tuncer Ayaz 2010-2013. All Rights Reserved.
# Copyright Ericsson AB 2010-2013. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#
# Author: Tuncer Ayaz
#

if [ $# -lt 8 ]
then
  echo "Usage: fakefop -c IGNORED -cache IGNORED -fo IGNORED -pdf OUTFILE"
  exit 1
fi

OUTFILE=$8

echo -n -e '%PDF-1.4\n%\0342\0343\0317\0323\n\n' > $OUTFILE

cat >> $OUTFILE <<EndOfFile
1 0 obj
<<
  /Type /Catalog
  /Pages 2 0 R
>>
endobj

2 0 obj
<<
  /Type /Pages
  /Kids [ 3 0 R ]
  /Count 1
>>
endobj

3 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /MediaBox [ 0 0 612 492 ]
  /Contents 5 0 R
  /Resources <<
    /Font <<
      /F1 4 0 R
    >>
  >>
>>
endobj

4 0 obj
<<
  /Type /Font
  /Subtype /Type1
  /Name /F1
  /BaseFont /Helvetica
  /Encoding /StandardEncoding
>>
endobj

5 0 obj
<<
  /Length 74
>>
stream
BT
/F1 24 Tf
10 400 Td
(\(placeholder PDF generated with fakefop\)) Tj
ET
endstream
endobj

xref
0 6
0000000000 65536 f
0000000016 00000 n
0000000070 00000 n
0000000136 00000 n
0000000291 00000 n
0000000410 00000 n

trailer
<<
  /Size 6
  /Root 1 0 R
>>

startxref
536
%%EOF
EndOfFile
