%%  Warning: Do not edit this file.  It was automatically
%%  generated by 'beam_makeops' on Mon Nov 16 12:53:08 2009.

-define(tag_u, 0).
-define(tag_i, 1).
-define(tag_a, 2).
-define(tag_x, 3).
-define(tag_y, 4).
-define(tag_f, 5).
-define(tag_h, 6).
-define(tag_z, 7).

