#!/usr/bin/env escript

main([Enc]) ->
  Data = {tuple, {list, lists:seq(1,1000000)}},
  io:setopts(group_leader(), [{encoding, list_to_atom(Enc)}]),
  file:write(group_leader(), term_to_binary(Data)),
  ok.
