## %CopyrightBegin%
##
## SPDX-License-Identifier: Apache-2.0
##
## Copyright Ericsson AB 2024-2026. All Rights Reserved.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## %CopyrightEnd%

##
## This workflow handles testing of pull requests and pushes.
## It also publishes some packages to any new Erlang/OTP release
##
## To speed this up it would be nice if one could share docker
## images inbetween different jobs, but at the moment this is
## not possible so we need to rebuild all of Erlang/OTP multiple
## times.
##
## Now that we have migrated to ghcr.io we use the
## built-in caching mechanisms of docker/build-push-action@v2.
## However as things are now we use docker directly to make things
## work due to historical reasons.
##

name: Build and check Erlang/OTP

on:
  push:
  pull_request:
  workflow_dispatch:

## We cancel any multiple runs from PRs, while runs from tags/branches are allowed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    permissions:
      contents:     write   # release creation
      packages:     write   # sbom upload
      attestations: write   # attest-sbom action
      id-token:     write   # attest-sbom action
      security-events: write
      actions:      write
      issues:       write
      pull-requests: write
    # this call will fail the first time because there is not yet in master
    # a reusable-main.yaml workflow, since it is introduced in a PR.
    # after the merge, any maint-XX branch that has this `main.yaml` will fetch
    # the CI configuration from `master`. the idea is that one should avoid creating
    # thin wrappers such as maint-27.yaml unless there is a strong need to encoded them.
    # in case of maint-27.yaml, the branch `maint-27` will have a wrapper in `main.yaml`
    # that calls `erlang/otp/.github/workflows/main-27.yaml@master`. we try to avoid
    # these specific wrappers, but OTP-27 was not producing the documentation nor other
    # artifacts (sbom) in the standard fashion.
    uses: erlang/otp/.github/workflows/reusable-main.yaml@master  # ratchet:exclude
    secrets:
      TRIGGER_ERLANG_ORG_BUILD: ${{ secrets.TRIGGER_ERLANG_ORG_BUILD }}
