## %CopyrightBegin%
##
## SPDX-License-Identifier: Apache-2.0
##
## Copyright Ericsson AB 2024-2026. All Rights Reserved.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## %CopyrightEnd%

##
## This workflow handles testing of pull requests and pushes.
## It also publishes some packages to any new Erlang/OTP release
##
## To speed this up it would be nice if one could share docker
## images inbetween different jobs, but at the moment this is
## not possible so we need to rebuild all of Erlang/OTP multiple
## times.
##
## Now that we have migrated to ghcr.io we use the
## built-in caching mechanisms of docker/build-push-action@v2.
## However as things are now we use docker directly to make things
## work due to historical reasons.
##

name: Build and check Erlang/OTP

on:
  push:
  pull_request:
  schedule:
      - cron: 0 1 * * *

## We cancel any multiple runs from PRs, while runs from tags/branches are allowed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
    ## Equivalent to github.event_name == 'pull_request' ? github.base_ref : github.ref_name
    BASE_BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
    ## 'true' if all steps should be built and all tests run
    FULL_BUILD_AND_CHECK: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'full-build-and-check') || github.event_name == 'schedule' }}
    ORT_VERSION: 77.0.0
    OTP_SBOM_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:

  check-beam:
    name: Forbid non-maintainers from committing BEAM files
    runs-on: ubuntu-latest
    if: github.repository == 'erlang/otp' && github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Detect modified BEAM files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          PERMISSION=$(gh api \
                       -H "Accept: application/vnd.github+json" \
                       -H "X-GitHub-Api-Version: 2022-11-28" \
                       /repos/{owner}/{repo}/collaborators/$PR_AUTHOR/permission --jq '.role_name')

          MODIFIED_BEAM_FILES=$(git diff --name-only --merge-base \
                                         ${{github.event.pull_request.base.sha}} \
                                         ${{github.event.pull_request.head.sha}} \
                                | grep '\.beam$' || true)
          if [[ "$PERMISSION" != "admin" && "$PERMISSION" != "maintain" && "$PERMISSION" != "Security Master" && -n "$MODIFIED_BEAM_FILES" ]]; then
             echo "::error::Workflow failed: Only maintainers can make modifications to '*.beam' files:"
             echo "$MODIFIED_BEAM_FILES"
             exit 1
          fi

  setup:
    name: Setup variables
    runs-on: ubuntu-latest
    outputs:
      base_branch:          ${{ steps.setup.outputs.base_branch }}
      full_build_and_check: ${{ steps.setup.outputs.full_build_and_check }}
      ort_version:          ${{ steps.setup.outputs.ort_version }}
      otp_sbom_version:     ${{ steps.setup.outputs.otp_sbom_version }}
      docs_base_url:        ${{ steps.setup.outputs.docs_base_url }}
    steps:
      - id: setup
        # github.event.pull_request.head.ref" is potentially untrusted.
        # we avoid using it directly in inline scripts. instead, pass it through an environment variable
        env:
          EVENT_NAME:    ${{ github.event_name }}
          PR_REPO:       ${{ github.event.pull_request.head.repo.full_name }}
          PR_HEAD_REF:   ${{ github.event.pull_request.head.ref }}
          REPO:          ${{ github.repository }}
          REF_NAME:      ${{ github.ref_name }}
        run: |
          echo "base_branch=${{ env.BASE_BRANCH }}" >> $GITHUB_OUTPUT
          echo "full_build_and_check=${{ env.FULL_BUILD_AND_CHECK }}" >> $GITHUB_OUTPUT
          echo "ort_version=${{ env.ORT_VERSION }}" >> $GITHUB_OUTPUT
          echo "otp_sbom_version=${{ env.OTP_SBOM_VERSION }}" >> $GITHUB_OUTPUT
          TAG=${GITHUB_REF#refs/tags/}
          VSN=${TAG#OTP-}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "vsn=${VSN}" >> $GITHUB_OUTPUT


          if [[ "$EVENT_NAME" == "pull_request" ]]; then
            echo "docs_base_url=${PR_REPO}/blob/${PR_HEAD_REF}/"   >> $GITHUB_OUTPUT
          else
            echo "docs_base_url=${REPO}/blob/${REF_NAME}/"         >> $GITHUB_OUTPUT
          fi

  pack:
    name: Build Erlang/OTP (64-bit)
    needs: setup
    uses: ./.github/workflows/reusable-pack.yaml
    permissions:
      contents: write
      id-token: write
    with:
      base_branch:          ${{ needs.setup.outputs.base_branch }}
      full_build_and_check: ${{ needs.setup.outputs.full_build_and_check }}
      ref_name:             ${{ github.ref_name }}
      base_ref:             ${{ github.base_ref }}
      pr_base_sha:          ${{ github.event.pull_request.base.sha }}
      bypass_erlang_repo:   false

  build-macos:
    name: Build Erlang/OTP (macOS)
    needs: pack
    if: needs.pack.outputs.build-c-code == 'true'
    uses: ./.github/workflows/reusable-build-macos.yaml
    with:
      base_branch: ${{ needs.setup.outputs.base_branch }}

  build-ios:
    name: Build Erlang/OTP (iOS)
    needs: pack
    if: needs.pack.outputs.build-c-code == 'true'

  build-windows:
    defaults:
      run:
        shell: wsl-bash {0}
    env:
      WXWIDGETS_VERSION: 3.2.6
    name: Build Erlang/OTP (Windows)
    runs-on: windows-2025
    needs: pack
    if: needs.pack.outputs.build-c-code == 'true'
    steps:
      - uses: Vampire/setup-wsl@6a8db447be7ed35f2f499c02c6e60ff77ef11278 # v6.0.0
        with:
          distribution: Ubuntu-18.04

      - name: Install WSL dependencies
        run: apt update && apt install -y make autoconf unzip

      - name: Install NSIS
        shell: cmd
        run: |
          choco install nsis --version 3.11.0

      - name: Install openssl
        shell: cmd
        run: |
          choco install openssl --version=3.1.1
          IF EXIST "c:\\Program Files\\OpenSSL-Win64" (move "c:\\Program Files\\OpenSSL-Win64" "c:\\OpenSSL-Win64") ELSE (move "c:\\Program Files\\OpenSSL" "c:\\OpenSSL-Win64")

      - name: Cache wxWidgets
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: wxWidgets
          key: wxWidgets-${{ env.WXWIDGETS_VERSION }}-${{ runner.os }}

      # actions/cache on Windows sometimes does not set cache-hit even though there was one. Setting it manually.
      - name: Set wxWidgets cache
        id: wxwidgets-cache
        env:
          WSLENV: GITHUB_OUTPUT/p
        run: |
          if [ -d wxWidgets ]; then
            echo "cache-hit=true" >> $GITHUB_OUTPUT
          else
            echo "cache-hit=false" >> $GITHUB_OUTPUT
          fi

      - name: Download wxWidgets
        if: steps.wxwidgets-cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/wxWidgets/wxWidgets/releases/download/v${{ env.WXWIDGETS_VERSION }}/wxWidgets-${{ env.WXWIDGETS_VERSION }}.zip
          unzip wxWidgets-${{ env.WXWIDGETS_VERSION }}.zip -d wxWidgets
          sed -i -r -e 's/wxUSE_POSTSCRIPT +0/wxUSE_POSTSCRIPT 1/' wxWidgets/include/wx/msw/setup.h
          sed -i -r -e 's/wxUSE_WEBVIEW_EDGE +0/wxUSE_WEBVIEW_EDGE 1/' wxWidgets/include/wx/msw/setup.h

      - name: Install WebView2
        if: steps.wxwidgets-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          cd wxWidgets\\3rdparty
          nuget install Microsoft.Web.WebView2 -Version 1.0.705.50 -Source https://api.nuget.org/v3/index.json
          rename Microsoft.Web.WebView2.1.0.705.50 webview2

      - name: Build wxWidgets
        if: steps.wxwidgets-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          cd wxWidgets\\build\\msw
          call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\Auxiliary\\Build\\vcvars64.bat"
          nmake TARGET_CPU=amd64 BUILD=release SHARED=0 DIR_SUFFIX_CPU= -f makefile.vc

      - name: Download source archive
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: otp_prebuilt

      - name: Compile Erlang
        run: |
          mkdir -p /mnt/c/opt/local64/pgm/
          cp -R wxWidgets /mnt/c/opt/local64/pgm/wxWidgets-${{ env.WXWIDGETS_VERSION }}
          tar -xzf ./otp_src.tar.gz
          cd otp
          export PATH="/mnt/c/Program Files (x86)/NSIS/bin":$PATH
          export ERL_TOP=`pwd`
          export MAKEFLAGS=-j$(($(nproc) + 2))
          export ERLC_USE_SERVER=true
          export ERTS_SKIP_DEPEND=true
          eval `./otp_build env_win32 x64`
          ./otp_build configure
          if cat erts/CONF_INFO ||
             grep -v "Static linking with OpenSSL 3.0" lib/*/CONF_INFO ||
             cat lib/*/SKIP ||
             cat lib/SKIP-APPLICATIONS; then
             exit 1
          fi
          ./otp_build boot -a
          ./otp_build release -a
          cp /mnt/c/opt/local64/pgm/wxWidgets-${{ env.WXWIDGETS_VERSION }}/3rdparty/webview2/runtimes/win-x64/native/WebView2Loader.dll $ERL_TOP/release/win32/erts-*/bin/
          ./otp_build debuginfo_win32
          ./otp_build installer_win32

      - name: Upload installer
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: otp_win32_installer
          path: otp/release/win32/otp*.exe

  build-flavors:
    name: Build Erlang/OTP (Types and Flavors)
    runs-on: ubuntu-latest
    needs: pack
    if: needs.pack.outputs.build-c-code == 'true'

    strategy:
      matrix:
        flavor: [jit, emu]
      fail-fast: false

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/build-base-image
        with:
            BASE_BRANCH: ${{ env.BASE_BRANCH }}
      - name: Build Erlang/OTP flavors and types
        run: |
            TYPES="opt debug lcnt asan gcov valgrind"
            FLAVORS="${{ matrix.flavor }}"
            for TYPE in ${TYPES}; do
              for FLAVOR in ${FLAVORS}; do
                echo "::group::{TYPE=$TYPE FLAVOR=$FLAVOR}"
                docker run otp \
                  "set -xe;

                   if [ '${TYPE}' = 'valgrind' ]; then sudo apt-get install -y valgrind bc; fi;

                   echo 'Setup start flags';
                   if [ '$TYPE' != 'opt' ]; then EMU_TYPE='-emu_type $TYPE'; fi;
                   if [ '$FLAVOR' = 'jit' ]; then
                      EMU_FLAVOR='smp'
                   else
                      EMU_FLAVOR='$FLAVOR'
                   fi;

                   echo 'Build type and flavor and test starting in source tree';
                   TYPE=$TYPE FLAVOR=$FLAVOR ./otp_build boot -a;
                   cerl -$TYPE -emu_flavor \$EMU_FLAVOR -noshell -s init stop;

                   echo 'Install and test installation';
                   sudo make install TYPE=$TYPE FLAVOR=$FLAVOR;
                   if [ $TYPE != 'valgrind' ] && [ $TYPE != 'asan' ]; then
                       erl \$EMU_TYPE -emu_flavor \$EMU_FLAVOR -noshell -s init stop;
                   fi

                   echo 'Release and test release'
                   ./otp_build release -a \$(pwd)/test_release/;
                   (cd \$(pwd)/test_release/ && ./Install -minimal \$(pwd));
                   TYPE=$TYPE FLAVOR=$FLAVOR ./otp_build release -a \$(pwd)/test_release;
                   if [ $TYPE != 'valgrind' ] && [ $TYPE != 'asan' ]; then
                       test_release/bin/erl \$EMU_TYPE -emu_flavor \$EMU_FLAVOR -noshell -s init stop;
                   fi"
                echo "::endgroup::"
              done
            done
      - name: Build Erlang/OTP JIT Win32 ABI
        if: ${{ matrix.flavor == 'jit' }}
        run: >
            docker run otp \
                'set -xe;
                 ./configure CFLAGS="$CFLAGS -DERTS_JIT_ABI_WIN32=1";
                 make && make TYPE=debug;
                 cerl -noshell -s init stop && cerl -debug -noshell -s init stop'

      - name: Build Erlang/OTP with LTTNG
        if: ${{ matrix.flavor == 'jit' }}
        run: >
            docker run otp \
                'set -xe;
                 sudo apt-get install -y lttng-tools;
                 ./configure --enable-dynamic-trace=lttng;
                 make && make TYPE=debug;
                 cerl -noshell -s init stop && cerl -debug -noshell -s init stop'

      - name: Start Erlang with various start options
        if: ${{ matrix.flavor == 'jit' }}
        run: |
            OPTIONS=("+JPperf true" "+JMsingle true" "+JDdump true")
            for OPTION in "${OPTIONS[@]}"; do
                docker run otp "erl ${OPTION} -noshell -s init stop"
            done

  modified-vendor-files:
    name: Check if vendor files changed
    runs-on: ubuntu-latest
    # this condition is necessary because github.base_ref only exists for pull_requests
    if: ${{ github.event_name == 'pull_request' }}
    outputs:
      vendor-files: ${{ steps.vendor-files.outputs.MODIFIED_FILES != '0' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Get modified vendor files
        id: vendor-files
        run: |
          echo "MODIFIED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep 'vendor\.info$' | wc -l || 1)" >> $GITHUB_OUTPUT

  # this is a call to a workflow_call
  pr-vendor-vulnerability-analysis:
    needs: modified-vendor-files
    if: ${{ needs.modified-vendor-files.outputs.vendor-files == 'true' && github.event_name == 'pull_request' && github.repository == 'erlang/otp'}}
    permissions:
      actions: read
    name: Vendor Vulnerability Scanning
    uses: ./.github/workflows/reusable-vendor-vulnerability-scanner.yml
    with:
      fail_if_cve: false
      checkout:    true
      version:     ${{ needs.setup.outputs.base_branch }}
      # `fail_if_cve` must always be `false`. the reason is that the reusable workflow tries to open
      # a GH Issue if it finds a vulnerability. however, this can only work on internal PRs or PRs coming
      # from a repo branch. this is a security limitation as otherwise, forked repos could create pull
      # requests against Erlang/OTP which start creating automatic issues.
    secrets: inherit

  build:
    name: Build Erlang/OTP
    runs-on: ubuntu-latest
    needs: pack
    if: needs.pack.outputs.build-c-code == 'true'

    strategy:
      matrix:
        type: [32-bit,cross-compile,clang]
      fail-fast: false

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/build-base-image
        with:
            BASE_BRANCH: ${{ env.BASE_BRANCH }}
            TYPE: ${{ matrix.type }}

  freebsd:
    name: Build Erlang/OTP (FreeBSD)
    runs-on: ubuntu-latest
    needs: pack
    if: needs.pack.outputs.build-c-code == 'true'
    steps:
      - name: Download source archive
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: otp_prebuilt
      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@c9f815bc7aa0d34c9fdd0619b034a32d6ca7b57e # v1
        with:
            usesh: true
            copyback: false
            prepare: |
              pkg update
              pkg upgrade -y
              pkg install -y bash gmake gtar autoconf ncurses pkgconf

            run: |
                tar -xzf ./otp_src.tar.gz
                cd otp
                export ERL_TOP=`pwd`
                export MAKEFLAGS=-j$(($(nproc) + 2))
                export ERLC_USE_SERVER=true
                export ERTS_SKIP_DEPEND=true
                ./configure
                gmake

  documentation:
    name: Build and Check Documentation
    needs:
      - setup
      - pack
    uses: ./.github/workflows/reusable-documentation.yaml
    secrets:
      TRIGGER_ERLANG_ORG_BUILD: ${{ secrets.TRIGGER_ERLANG_ORG_BUILD }}
    with:
      base_branch:              ${{ needs.setup.outputs.base_branch }}
      base_url:                 ${{ needs.setup.outputs.docs_base_url  }}
      trigger_erlang_org_build: ${{ github.ref_name == 'master' && github.repository == 'erlang/otp' }}

  static:
    name: Run static analysis
    runs-on: ubuntu-latest
    needs: pack
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/build-base-image
        with:
            BASE_BRANCH: ${{ env.BASE_BRANCH }}
        ## Check formatting of cpp code
      - name: Check format
        run: docker run otp "make format-check"
        ## Run dialyzer
      - name: Run dialyzer
        run: docker run -v $PWD/:/github otp '/github/scripts/run-dialyzer'
      - name: Check OSSF compiler flags
        uses: ./.github/actions/ossf-compiler-flags-scanner
        with:
          upload: ${{ github.repository == 'erlang/otp' || github.event_name != 'push' }}

  test:
    name: Test Erlang/OTP
    runs-on: ubuntu-latest
    needs: pack
    if: needs.pack.outputs.changes != '[]'
    strategy:
      matrix:
        # type: ${{ fromJson(needs.pack.outputs.all) }}
        type: ${{ fromJson(needs.pack.outputs.changes) }}
        # type: ["os_mon","sasl"]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/build-base-image
        with:
            BASE_BRANCH: ${{ env.BASE_BRANCH }}
      - name: Run tests
        id: run-tests
        run: |
          set -x
          mkdir $PWD/make_test_dir
          APP="${{ matrix.type }}"
          ## Need to specialize for epmd, emulator and debug
          case "${APP}" in
            emulator) DIR=erts/emulator/ ;;
            epmd) DIR=erts/epmd ;;
            debug) DIR=lib/os_mon; APP=os_mon; TYPE=debug ;;
            *) DIR=lib/${{ matrix.type }} ;;
          esac
          ## Remove systemd-coredump
          ! sudo apt remove systemd-coredump
          ## Removing systemd-coredump, caused apport to be installed instead, so we disable it
          ! sudo service apport stop
          sudo sysctl -w dev.tty.legacy_tiocsti=1
          sudo bash -c "echo 'core.%p' > /proc/sys/kernel/core_pattern"
          docker run --ulimit core=-1 --ulimit nofile=5000:5000 --pids-limit 1024 \
            -e CTRUN_TIMEOUT=90 -e SPEC_POSTFIX=gh \
            -e TEST_NEEDS_RELEASE=true -e "RELEASE_ROOT=/buildroot/otp/Erlang ∅⊤℞" \
            -e EXTRA_ARGS="-ct_hooks cth_surefire [{path,\"/buildroot/otp/$DIR/make_test_dir/${{ matrix.type }}_junit.xml\"}]" \
            -v "$PWD/make_test_dir:/buildroot/otp/$DIR/make_test_dir" \
            -v "$PWD/scripts:/buildroot/otp/scripts" \
            otp "./otp_build download_gdb_tools && make emulator && make TYPE=${TYPE} && make ${APP}_test TYPE=${TYPE}"
          ## Rename os_mon to debug for debug build
          if [ "$APP" != "${{ matrix.type }}" ]; then
            mv make_test_dir/${APP}_test "make_test_dir/${{ matrix.type }}_test"
          fi
      - name: Cleanup tests
        if: ${{ !cancelled() }}
        run: |
          rm -rf make_test_dir/otp || true
          sudo bash -c "chown -R `whoami` make_test_dir && chmod -R +r make_test_dir"
          tar czf ${{ matrix.type }}_test_results.tar.gz make_test_dir
      - name: Upload test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ !cancelled() }}
        with:
          name: ${{ matrix.type }}_test_results
          path: ${{ matrix.type }}_test_results.tar.gz

  system-test:
    name: Test Erlang/OTP (system)
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }} # Run even if the need has failed
    needs: test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/build-base-image
        with:
            BASE_BRANCH: ${{ env.BASE_BRANCH }}
      - name: Download test results
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      - name: Merge test results
        run: |
          shopt -s nullglob
          mkdir -p make_test_dir
          for file in *_test_results/*.tar.gz; do
            tar xzf $file
          done
          docker run -v $PWD/make_test_dir:/buildroot/otp/erts/make_test_dir otp \
            "ct_run -refresh_logs /buildroot/otp/erts/make_test_dir"
      - name: Run system tests
        run: |
          ## Remove systemd-coredump
          ! sudo apt remove systemd-coredump
          ## Removing systemd-coredump, caused apport to be installed instead, so we disable it
          ! sudo service apport stop
          sudo bash -c "echo 'core.%p' > /proc/sys/kernel/core_pattern"
          docker run --ulimit core=-1 --ulimit nofile=5000:5000 --pids-limit 512 \
            -e CTRUN_TIMEOUT=90 -e SPEC_POSTFIX=gh \
            -e EXTRA_ARGS="-ct_hooks cth_surefire [{path,\"/buildroot/otp/erts/make_test_dir/system_junit.xml\"}]" \
            -e OTP_DAILY_BUILD_TOP_DIR=/buildroot/otp/erts/make_test_dir \
            -v $PWD/make_test_dir:/buildroot/otp/erts/make_test_dir otp \
            "make system_test"
      - name: Cleanup tests
        if: ${{ !cancelled() }}
        run: |
          rm -rf make_test_dir/otp || true
          tar czf test_results.tar.gz make_test_dir
          # Translate file="/buildroot/otp/lib/os_mon/make_test_dir/os_mon_test/cpu_sup_SUITE.erl"
          # to file="lib/os_mon/test/cpu_sup_SUITE.erl"
          sed -i -e 's:file="/buildroot/otp/:file=":g' \
              -e 's:\(file="[^/]*/[^/]*/\)make_test_dir/[^/]*:\1test:g' \
              -e 's:\(file="erts/\)make_test_dir/[^/]*:\1test:g' \
              make_test_dir/*_junit.xml
      - name: Upload test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: ${{ !cancelled() }}
        with:
          name: test_results
          path: test_results.tar.gz
      - name: Upload Test Results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Unit Test Results
          path: |
            make_test_dir/*_junit.xml

  ## If you want to speedup this step for testing the easiest way is to create
  ## these two commits:
  ##
  ##   git rm -rf lib erts system && git revert HEAD
  ##
  ## and then create a step that that does this:
  ##
  ##   - name: SBOM Sha
  ##     run: echo "sha=$(git rev-parse HEAD~1)" >> $GITHUB_OUTPUT
  ##
  ## and then make sure to use that sha instead of env.OTP_SBOM_VERSION
  sbom:
    name: Create SBOM
    needs:
      - setup
      - pack
    uses: ./.github/workflows/reusable-sbom.yaml
    permissions:
      contents: write
      actions:  read
      packages: read
      id-token: write
    with:
      base_branch:                   ${{ needs.setup.outputs.base_branch }}
      full_build_and_check:          ${{ needs.setup.outputs.full_build_and_check }}
      ref_name:                      ${{ github.ref_name }}
      base_ref:                      ${{ github.base_ref }}
      pr_base_sha:                   ${{ github.event.pull_request.base.sha }}
      otp_sbom_version:              ${{ needs.setup.outputs.otp_sbom_version }}
      ort_version:                   ${{ needs.setup.outputs.ort_version }}
      fail_on_violations:            ${{ github.ref_type == 'tag' && '' || 'violations,issues' }}
      upload_sbom_to_dependency_api: ${{ github.event_name == 'pull_request' &&
                                         github.event.action == 'closed'     &&
                                         github.event.pull_request.merged == true }}

  # this is needed before every release job.
  # sets up variables for the release
  release-setup:
    name: Setup Release variables
    runs-on: ubuntu-latest
    outputs:
      base_branch:          ${{ steps.release-setup.outputs.base_branch }}
      ort_version:          ${{ steps.release-setup.outputs.ort_version }}
      otp_sbom_version:     ${{ steps.release-setup.outputs.otp_sbom_version }}
      tag:                  ${{ steps.release-setup.outputs.tag }}
      vsn:                  ${{ steps.release-setup.outputs.vsn }}
    steps:
      - id: release-setup
        run: |
          echo "base_branch=${{ env.BASE_BRANCH }}" >> $GITHUB_OUTPUT
          echo "ort_version=${{ env.ORT_VERSION }}" >> $GITHUB_OUTPUT
          echo "otp_sbom_version=${{ env.OTP_SBOM_VERSION }}" >> $GITHUB_OUTPUT
          echo "tag=${{ env.BASE_BRANCH }}" >> $GITHUB_OUTPUT
          echo "vsn=$(echo ${{ env.BASE_BRANCH }} | cut -d- -f2)" >> $GITHUB_OUTPUT

  ## If this is an "OTP-*" tag that has been pushed we do some release work
  release:
    name: Release Erlang/OTP
    needs:
      - setup
      - sbom
      - documentation
    permissions:
      contents:     write
      attestations: write
      id-token:     write
    if: startsWith(github.ref, 'refs/tags/OTP-') && github.repository == 'erlang/otp'
    uses: ./.github/workflows/reusable-release.yaml
    with:
      otp_sbom_version: ${{ needs.release-setup.outputs.otp_sbom_version }}
      tag:              ${{ needs.release-setup.outputs.tag }}
      vsn:              ${{ needs.release-setup.outputs.vsn }}
      base_branch:      ${{ needs.release-setup.outputs.base_branch }}
    secrets: inherit

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Event File
          path: ${{ github.event_path }}
