# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2024-2026. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

name: Test Erlang/OTP (system)
run-name: "[${{ inputs.base_branch }}] Test Erlang/OTP (system)"

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string

env:
  BASE_BRANCH: ${{ inputs.base_branch }}

permissions:
  contents: read

# NOTE: This job should only be executed on the callee with `needs: pack`
jobs:
  system-test:
    name: Test Erlang/OTP (system)
    runs-on: ubuntu-latest
    permissions:
      contents: read   # actions/checkout + ./.github/actions/build-base-image
      actions: write   # actions/download-artifact + actions/upload-artifact
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - uses: ./.github/actions/build-base-image
        with:
            BASE_BRANCH: ${{ env.BASE_BRANCH }}

      - name: Download test results
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # ratchet:actions/download-artifact@v6.0.0
      - name: Merge test results
        run: |
          shopt -s nullglob
          mkdir -p make_test_dir
          for file in *_test_results/*.tar.gz; do
            tar xzf $file
          done
          docker run -v $PWD/make_test_dir:/buildroot/otp/erts/make_test_dir otp \
            "ct_run -refresh_logs /buildroot/otp/erts/make_test_dir"
      - name: Run system tests
        run: |
          ## Remove systemd-coredump
          ! sudo apt remove systemd-coredump
          ## Removing systemd-coredump, caused apport to be installed instead, so we disable it
          ! sudo service apport stop
          sudo bash -c "echo 'core.%p' > /proc/sys/kernel/core_pattern"
          docker run --ulimit core=-1 --ulimit nofile=5000:5000 --pids-limit 512 \
            -e CTRUN_TIMEOUT=90 -e SPEC_POSTFIX=gh \
            -e EXTRA_ARGS="-ct_hooks cth_surefire [{path,\"/buildroot/otp/erts/make_test_dir/system_junit.xml\"}]" \
            -e OTP_DAILY_BUILD_TOP_DIR=/buildroot/otp/erts/make_test_dir \
            -v $PWD/make_test_dir:/buildroot/otp/erts/make_test_dir otp \
            "make system_test"
      - name: Cleanup tests
        if: ${{ !cancelled() }}
        run: |
          rm -rf make_test_dir/otp || true
          tar czf test_results.tar.gz make_test_dir
          # Translate file="/buildroot/otp/lib/os_mon/make_test_dir/os_mon_test/cpu_sup_SUITE.erl"
          # to file="lib/os_mon/test/cpu_sup_SUITE.erl"
          sed -i -e 's:file="/buildroot/otp/:file=":g' \
              -e 's:\(file="[^/]*/[^/]*/\)make_test_dir/[^/]*:\1test:g' \
              -e 's:\(file="erts/\)make_test_dir/[^/]*:\1test:g' \
              make_test_dir/*_junit.xml
      - name: Upload test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6.0.0
        if: ${{ !cancelled() }}
        with:
          name: test_results
          path: test_results.tar.gz
      - name: Upload Test Results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6.0.0
        with:
          name: Unit Test Results
          path: |
            make_test_dir/*_junit.xml
