# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2024-2026. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

name: Test Erlang/OTP
run-name: "[${{ inputs.base_branch }}] Test Erlang/OTP"

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      changes:
        required: true
        type: string

env:
  BASE_BRANCH: ${{ inputs.base_branch }}

permissions:
  contents: read

# NOTE: This job should only be executed on the callee with `needs: pack`
jobs:
  test:
    name: Test Erlang/OTP
    runs-on: ubuntu-latest
    permissions:
      contents: read   # actions/checkout + ./.github/actions/build-base-image
      actions:  write  # actions/upload-artifact
    strategy:
      matrix:
        # type: ${{ fromJson(needs.pack.outputs.all) }}
        type: ${{ fromJson(inputs.changes) }}
        # type: ["os_mon","sasl"]
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/build-base-image
        with:
            BASE_BRANCH: ${{ env.BASE_BRANCH }}
      - name: Run tests
        id: run-tests
        env:
          MATRIX_TYPE: ${{ matrix.type }}
        run: |
          set -x
          mkdir $PWD/make_test_dir
          APP="${MATRIX_TYPE}"
          ## Need to specialize for epmd, emulator and debug
          case "${APP}" in
            emulator) DIR=erts/emulator/ ;;
            epmd) DIR=erts/epmd ;;
            debug) DIR=lib/os_mon; APP=os_mon; TYPE=debug ;;
            *) DIR=lib/${MATRIX_TYPE} ;;
          esac
          ## Remove systemd-coredump
          ! sudo apt remove systemd-coredump
          ## Removing systemd-coredump, caused apport to be installed instead, so we disable it
          ! sudo service apport stop
          sudo sysctl -w dev.tty.legacy_tiocsti=1
          sudo bash -c "echo 'core.%p' > /proc/sys/kernel/core_pattern"
          docker run --ulimit core=-1 --ulimit nofile=5000:5000 --pids-limit 1024 \
            -e CTRUN_TIMEOUT=90 -e SPEC_POSTFIX=gh \
            -e TEST_NEEDS_RELEASE=true -e "RELEASE_ROOT=/buildroot/otp/Erlang ∅⊤℞" \
            -e EXTRA_ARGS="-ct_hooks cth_surefire [{path,\"/buildroot/otp/$DIR/make_test_dir/${MATRIX_TYPE}_junit.xml\"}]" \
            -v "$PWD/make_test_dir:/buildroot/otp/$DIR/make_test_dir" \
            -v "$PWD/scripts:/buildroot/otp/scripts" \
            otp "./otp_build download_gdb_tools && make emulator && make TYPE=${TYPE} && make ${APP}_test TYPE=${TYPE}"
          ## Rename os_mon to debug for debug build
          if [ "$APP" != "${MATRIX_TYPE}" ]; then
            mv make_test_dir/${APP}_test "make_test_dir/${MATRIX_TYPE}_test"
          fi
      - name: Cleanup tests
        if: ${{ !cancelled() }}
        env:
          MATRIX_TYPE: ${{ matrix.type }}
        run: |
          rm -rf make_test_dir/otp || true
          sudo bash -c "chown -R `whoami` make_test_dir && chmod -R +r make_test_dir"
          tar czf ${MATRIX_TYPE}_test_results.tar.gz make_test_dir
      - name: Upload test results
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6.0.0
        if: ${{ !cancelled() }}
        with:
          name: ${{ matrix.type }}_test_results
          path: ${{ matrix.type }}_test_results.tar.gz
