## %CopyrightBegin%
##
## SPDX-License-Identifier: Apache-2.0
##
## Copyright Ericsson AB 2024-2026. All Rights Reserved.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## %CopyrightEnd%

name: Scheduled Build and check Erlang/OTP

on:
  workflow_dispatch:
  schedule:
      - cron: 0 1 * * *

permissions:
  contents: read

jobs:
  maintained-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.repository == 'erlang/otp'
    # if: github.event_name != 'workflow_dispatch' # used for testing
    outputs:
       versions: ${{ steps.get-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - id: get-versions
        name: Fetch latest 3 OTP versions
        run: |
          echo "versions=$(.github/scripts/get-supported-branches.sh)" >> "$GITHUB_OUTPUT"

  run-scheduled-build:
    # Fan out and create requests to run build on multiple maintained branches.
    # this simply triggers scheduled runs
    needs: maintained-versions
    runs-on: ubuntu-latest
    if: github.repository == 'erlang/otp'
    strategy:
      matrix:
        type: ${{ fromJson(needs.maintained-versions.outputs.versions) }}
      fail-fast: false
    permissions:
      # 'write' permission to trigger a workflow in the same repo
      actions: write
    steps:
      - name: Trigger Build and Check
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }} # in testing cases, this is your fork, e.g., kikofernandez/otp
          MATRIX_TYPE: ${{ matrix.type }}
        run: |
          gh workflow run main.yaml --repo ${REPO} --ref ${MATRIX_TYPE}
