#!/bin/bash
# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2017-2025. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

# ./create-ssh-image openssh 7.3p1 openssl 1.0.2m [in-file]

case $1 in
    openssh)
        FAMssh=openssh
        VERssh=$2
        LINK=https://ftp.eu.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-${VERssh}.tar.gz
        TMP=tmp.tar.gz
    ;;
    *)
        echo "Unsupported: $1"
        exit 2
esac

FAMssl=$3
VERssl=$4
BASE_VER=$5

INPUT_FILE=$6

VER=${FAMssh}${VERssh}-${FAMssl}${VERssl}-${BASE_VER}

case $FAMssl$VERssl in
    openssl3*)
        LIB_DIR="lib64"
    ;;
    *)
        LIB_DIR="lib"
    ;;
esac

# This way of fetching the tar-file separate from the docker commands makes
# http-proxy handling way easier. The wget command handles the $https_proxy
# variable while the docker command must have /etc/docker/something changed
# and the docker server restarted. That is not possible without root access.

# Make a Dockerfile. This method simplifies env variable handling considerably:
cat - > TempDockerFile <<EOF

    FROM ssh_compat_suite_img-${FAMssl}:${VERssl}-${BASE_VER}
    ARG  DEBIAN_FRONTEND=noninteractive

    LABEL openssh-version=${VER}

    WORKDIR /buildroot

    COPY ${TMP} .
    RUN  tar xf ${TMP}

    # Build and install

    WORKDIR ${FAMssh}-${VERssh}

    # Probably VERY OpenSSH dependent...:
    RUN ./configure --without-pie \
                    --prefix=/buildroot/ssh \
                    --with-ssl-dir=/buildroot/ssl \
                    --with-pam \
                    LDFLAGS=-Wl,-R/buildroot/ssl/${LIB_DIR}
    RUN  make
    RUN  make install
    RUN  echo UsePAM yes >> /buildroot/ssh/etc/sshd_config

    RUN echo Built ${VER}

    # Start the daemon, but keep it in foreground to avoid killing the container
    CMD ["/buildroot/ssh/sbin/sshd", "-D", "-e", "-p", "1234"]

EOF

# Fetch the tar file. This could be done in an "ADD ..." in the Dockerfile,
# but then we hit the proxy problem...

if [[ "x$INPUT_FILE" == "x" ]]
then
    wget -O $TMP $LINK

elif [[ "x$INPUT_FILE" != "x$TMP" ]]
then
    echo "Use $INPUT_FILE for input"
    cp $INPUT_FILE $TMP
fi

# Build the image:
docker build -t ssh_compat_suite_img-ssh:$VER -f ./TempDockerFile .
CODE=$?

# Cleaning
rm -fr ./TempDockerFile $TMP

exit $CODE
