#!/bin/bash
# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2017-2025. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

WHAT_TO_DO=$1

function create_one_image ()
{
    SSH_FAM=$1
    SSH_VER=$2

    pushd ${SCRIPT_DIR}

    case $SSH_FAM in
    openssh)
        SSL_FAM=$3
        SSL_VER=$4
        BASE_VER=$5
        if ./create-ssl-image $SSL_FAM $SSL_VER $BASE_VER; then
            if ./create-ssh-image $SSH_FAM $SSH_VER $SSL_FAM $SSL_VER $BASE_VER; then
                popd
            else
                echo "Create $SSH_FAM $SSH_VER on $SSL_FAM $SSL_VER failed." >&2
                popd
                exit 3
            fi
        else
            echo "Create $SSL_FAM $SSL_VER failed." >&2
            popd
            exit 2
        fi
    ;;
    dropbear)
        BASE_VER=$3
        if ! ./create-dropbear-image $SSH_FAM $SSH_VER $BASE_VER; then
            echo "Create $SSH_FAM $SSH_VER failed." >&2
            popd
            exit 2
        fi
        popd
    ;;
    *)
        echo "Unsupported: $1"
        popd
        exit
    esac
}


case ${WHAT_TO_DO} in
    list)
    ;;
    listatoms)
        PRE="["
        POST="]"
        C=\'
        COMMA=,
    ;;
    build_one)
        if [[ $# == 6 ]]; then
            create_one_image $2 $3 $4 $5 $6
            exit
        elif [[ $# == 4 ]]; then
            create_one_image $2 $3 $4
            exit
        else
            echo "$0 build_one openssh SSH_ver openssl SSL_ver BASE_ver | build_one dropbear SSH_ver BASE_ver"
            exit 
        fi
    ;;
    build_all)
    ;;
    *)
        echo "$0 list | listatoms | build_one openssh SSH_ver openssl SSL_ver BASE_ver | build_one dropbear SSH_ver BASE_ver | build_all"
        exit
    ;;
esac


echo -n $PRE
FIRST=true
while read LINE; do
    [[ "$LINE" == \#* || "$LINE" == "" ]] && continue
    case ${WHAT_TO_DO} in
        list*)
            $FIRST || echo $COMMA
            echo -n $C$LINE$C
            FIRST=false
        ;;
        build_all)
            create_one_image $LINE
        ;;
    esac
done < ${SCRIPT_DIR}/../versions.txt
echo $POST
