#!/bin/sh
# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2018-2025. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

# ./create-dropbear-ssh

# This way of fetching the tar-file separate from the docker commands makes
# http-proxy handling way easier. The wget command handles the $https_proxy
# variable while the docker command must have /etc/docker/something changed
# and the docker server restarted. That is not possible without root access.

# Make a Dockerfile. This method simplifies env variable handling considerably:
cat - > TempDockerFile <<EOF

    FROM ubuntubuildbase

    WORKDIR /buildroot

    RUN apt-get -y update
    RUN apt-get -y upgrade
    RUN apt-get -y install openssh-sftp-server
%%    RUN echo 81 | apt-get -y install dropbear

EOF

# Build the image:
docker build -t ssh_compat_suite-ssh-dropbear -f ./TempDockerFile .

# Cleaning
rm -fr ./TempDockerFile $TMP
