# %CopyrightBegin%
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright Ericsson AB 2024-2025. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%

name: Open Source Security Foundation

inputs:
    upload:
        description: 'Upload sarif results using codeql'
        default: false

runs:
    using: composite
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
            repository: ossf/wg-best-practices-os-developers
            sparse-checkout: docs/Compiler-Hardening-Guides/compiler-options-scraper
            path: ossf
    
      - name: Setup compiler options scraper
        shell: bash -eo pipefail {0}
        run: |
          pip3 install -r ossf/docs/Compiler-Hardening-Guides/compiler-options-scraper/requirements.txt
          python3 ossf/docs/Compiler-Hardening-Guides/compiler-options-scraper/main.py
          cat compiler-options.json

      - name: Run compiler flag comparison
        shell: bash -eo pipefail {0}
        run: |
          docker run -v `pwd`/.github/scripts:/github --entrypoint "" otp \
            bash -c "/github/ossf-sarif-generator.es '$(cat compiler-options.json)'" > results.sarif

      - name: "Upload artifact"
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
            name: SARIF file
            path: results.sarif

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        if: ${{ !cancelled() && inputs.upload == 'true' }}
        uses: github/codeql-action/upload-sarif@b13d724d35ff0a814e21683638ed68ed34cf53d1 # ratchet:github/codeql-action/upload-sarif@v3.29.7
        with:
            sarif_file: results.sarif