#
# %CopyrightBegin%
#
# Copyright Ericsson AB 2000-2010. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# %CopyrightEnd%
#
EFLAGS=+debug_info
all: guards.@EMULATOR@ lists1.@EMULATOR@ my_lists.@EMULATOR@ \
     ordsets1.@EMULATOR@ test.@EMULATOR@ test1.@EMULATOR@

guards.@EMULATOR@: guards.erl
	erlc $(EFLAGS) guards.erl

lists1.@EMULATOR@: lists1.erl
	erlc $(EFLAGS) lists1.erl

my_lists.@EMULATOR@: my_lists.erl
	erlc $(EFLAGS) my_lists.erl

ordsets1.@EMULATOR@: ordsets1.erl
	erlc $(EFLAGS) ordsets1.erl

test.@EMULATOR@: test.erl
	erlc $(EFLAGS) test.erl

test1.@EMULATOR@: test1.erl
	erlc $(EFLAGS) test1.erl
