#
# %CopyrightBegin%
#
# Copyright Ericsson AB 2000-2010. All Rights Reserved.
#
# The contents of this file are subject to the Erlang Public License,
# Version 1.1, (the "License"); you may not use this file except in
# compliance with the License. You should have received a copy of the
# Erlang Public License along with this software. If not, it can be
# retrieved online at http://www.erlang.org/.
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
#
# %CopyrightEnd%
#
EFLAGS=+debug_info
all: guards.@EMULATOR@ lists1.@EMULATOR@ my_lists.@EMULATOR@ \
     ordsets1.@EMULATOR@ test.@EMULATOR@ test1.@EMULATOR@

guards.@EMULATOR@: guards.erl
	erlc $(EFLAGS) guards.erl

lists1.@EMULATOR@: lists1.erl
	erlc $(EFLAGS) lists1.erl

my_lists.@EMULATOR@: my_lists.erl
	erlc $(EFLAGS) my_lists.erl

ordsets1.@EMULATOR@: ordsets1.erl
	erlc $(EFLAGS) ordsets1.erl

test.@EMULATOR@: test.erl
	erlc $(EFLAGS) test.erl

test1.@EMULATOR@: test1.erl
	erlc $(EFLAGS) test1.erl
